// AF+ 13.0.0 — Cloud runtime: Google Sheets + Netlify + importação unificada Garmin/Zepp/Strava.
(function(){
  const VERSION='13.0.0';
  function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
  function fitKm(raw){const x=n(raw);return x>0?x/100000:0}
  function fitMin(raw){const x=n(raw);return x>0?x/1000/60:0}
  function stageType(i,name=''){const s=String(name||'').toLowerCase();if(s.includes('walk')||s.includes('camin'))return'Caminhada';if(s.includes('warm')||s.includes('aquec'))return'Aquecimento';if(s.includes('cool')||s.includes('desaquec'))return'Desaquecimento';if(Number(i)===1)return'Recuperação';return'Corrida'}
  function validateActivity(a){const w=[];if(n(a.executedDistanceKm)<0||n(a.executedDistanceKm)>500)w.push('distância fora da faixa esperada');if(n(a.executedDurationMin)<0||n(a.executedDurationMin)>1440)w.push('duração fora da faixa esperada');if(n(a.executedDistanceKm)>0&&n(a.executedDurationMin)>0){const p=n(a.executedDurationMin)/n(a.executedDistanceKm);if(p<2||p>40)w.push('ritmo fora da faixa esperada')}if(n(a.avgHr)>230||n(a.maxHr)>250)w.push('frequência cardíaca fora da faixa esperada');a.validationStatus=w.length?'revisar':'ok';a.validationWarnings=w.join('; ');return a}

  function parseFitCloud(buffer,source,fileName='atividade.fit'){
    const view=new DataView(buffer);if(view.byteLength<14)throw new Error('FIT muito pequeno ou corrompido');
    const headerSize=view.getUint8(0),dataSize=view.getUint32(4,true);const sig=String.fromCharCode(view.getUint8(8),view.getUint8(9),view.getUint8(10),view.getUint8(11));if(sig!=='.FIT')throw new Error('Assinatura FIT inválida');
    const dataEnd=Math.min(view.byteLength,headerSize+dataSize),defs=new Map(),sessions=[],laps=[],steps=[];let offset=headerSize,lastTimestamp=null;
    while(offset<dataEnd){
      const hdr=view.getUint8(offset++),compressed=!!(hdr&128);
      if(compressed){const local=(hdr>>5)&3,def=defs.get(local);if(!def)break;const vals={};for(const f of def.fields){if(f.num===253)continue;const out=fitReadValue(view,offset,f.size,f.base,def.little);vals[f.num]=out[0];offset=out[1]}for(const f of def.devFields)offset+=f.size;if(lastTimestamp!=null){let ts=(lastTimestamp&~31)|(hdr&31);if(ts<lastTimestamp)ts+=32;vals[253]=ts;lastTimestamp=ts}if(def.global===18)sessions.push(vals);if(def.global===19)laps.push(vals);if(def.global===27)steps.push(vals);continue}
      const isDef=!!(hdr&64),hasDev=!!(hdr&32),local=hdr&15;
      if(isDef){if(offset+5>dataEnd)break;offset++;const arch=view.getUint8(offset++),little=arch===0;const global=view.getUint16(offset,little);offset+=2;const count=view.getUint8(offset++),fields=[];for(let i=0;i<count;i++){fields.push({num:view.getUint8(offset),size:view.getUint8(offset+1),base:view.getUint8(offset+2)});offset+=3}const devFields=[];if(hasDev){const dc=view.getUint8(offset++);for(let i=0;i<dc;i++){devFields.push({num:view.getUint8(offset),size:view.getUint8(offset+1),devIndex:view.getUint8(offset+2)});offset+=3}}defs.set(local,{global,little,fields,devFields});continue}
      const def=defs.get(local);if(!def)break;const vals={};for(const f of def.fields){const out=fitReadValue(view,offset,f.size,f.base,def.little);vals[f.num]=out[0];offset=out[1];if(f.num===253&&Number.isFinite(Number(out[0])))lastTimestamp=Number(out[0])}for(const f of def.devFields)offset+=f.size;if(def.global===18)sessions.push(vals);if(def.global===19)laps.push(vals);if(def.global===27)steps.push(vals);
    }
    const make=(s,i)=>{
      const dur=fitMin(s[8]??s[7]),dist=fitKm(s[9]),workoutName=String(s[110]||'').trim(),modality=fitSportName(s[5],s[6],'');
      const execStages=laps.map((l,j)=>{const sd=fitMin(l[8]??l[7]),sk=fitKm(l[9]),step=steps[j]||{};const cad=n(l[17]),pace=sd>0&&sk>0?sd/sk:0;return {order:j+1,type:String(step[0]||'').trim()?stageType(step[7],step[0]):((cad>0&&cad<55)||(pace>10.4&&sd<=3)?'Caminhada':'Corrida'),name:String(step[0]||''),executedDurationMin:sd,executedDistanceKm:sk,executedPaceMinKm:pace,avgHr:n(l[15]),maxHr:n(l[16]),cadenceAvg:cad,calories:n(l[11]),elevationM:n(l[21]),source:'FIT lap'}}).filter(x=>x.executedDurationMin>=0.05||x.executedDistanceKm>=0.005);
      const a={id:`impact-${Date.now()}-${i}-${Math.random().toString(36).slice(2,7)}`,date:fitDateFromTimestamp(s[2]??s[253])||today(),modality,status:'executado',source,workoutName,executedDurationMin:dur,activeTimeMin:dur,totalTimeMin:fitMin(s[7]),executedDistanceKm:dist,executedPaceMinKm:dist>0&&dur>0?dur/dist:0,avgSpeedKmh:dur>0?dist/(dur/60):0,avgHr:n(s[16]),maxHr:n(s[17]),calories:n(s[11]),elevationM:n(s[22]),cadenceAvg:n(s[18]),externalId:fileName,executedStages:execStages,executedStagesJson:JSON.stringify(execStages),originalData:JSON.stringify({fileName,fitSession:s,fitLaps:laps,fitWorkoutSteps:steps})};a.fingerprint=trainingFingerprint(a);return validateActivity(a)
    };
    if(sessions.length)return sessions.map(make);
    throw new Error('Nenhuma sessão encontrada no FIT');
  }

  function parseTrackCloud(text,source,fileName){
    const doc=new DOMParser().parseFromString(text,'application/xml');const pts=[...doc.querySelectorAll('trkpt, Trackpoint')];if(!pts.length)return[];
    const laps=[...doc.querySelectorAll('Lap')];
    const getTime=p=>p.querySelector('time, Time')?.textContent||'';const firstTime=getTime(pts[0]);const lastTime=getTime(pts[pts.length-1]);
    const lapStages=laps.map((l,i)=>{const sec=n(l.querySelector('TotalTimeSeconds')?.textContent),km=n(l.querySelector('DistanceMeters')?.textContent)/1000;return {order:i+1,type:'Etapa',executedDurationMin:sec/60,executedDistanceKm:km,executedPaceMinKm:sec>0&&km>0?(sec/60)/km:0,avgHr:n(l.querySelector('AverageHeartRateBpm Value, AverageHeartRateBpm > Value')?.textContent),maxHr:n(l.querySelector('MaximumHeartRateBpm Value, MaximumHeartRateBpm > Value')?.textContent),cadenceAvg:n(l.querySelector('Cadence')?.textContent),calories:n(l.querySelector('Calories')?.textContent),source:'TCX Lap'}}).filter(x=>x.executedDurationMin||x.executedDistanceKm);
    let totalSec=lapStages.reduce((s,x)=>s+x.executedDurationMin*60,0),dist=lapStages.reduce((s,x)=>s+x.executedDistanceKm,0);
    if(!totalSec&&firstTime&&lastTime)totalSec=Math.max(0,(new Date(lastTime)-new Date(firstTime))/1000);
    if(!dist){const dm=[...doc.querySelectorAll('DistanceMeters')].map(x=>n(x.textContent)).filter(Boolean);dist=dm.length?Math.max(...dm)/1000:0}
    const hrs=pts.map(p=>n(p.querySelector('HeartRateBpm Value, HeartRateBpm > Value')?.textContent)).filter(Boolean),dur=totalSec/60;const workoutName=(doc.querySelector('Course > Name, trk > name')?.textContent||'').trim();
    const a={id:'impact-'+Date.now(),date:firstTime?new Date(firstTime).toISOString().slice(0,10):today(),modality:'Corrida',status:'executado',source,workoutName,executedDurationMin:dur,activeTimeMin:dur,totalTimeMin:dur,executedDistanceKm:dist,executedPaceMinKm:dist>0&&dur>0?dur/dist:0,avgSpeedKmh:dur>0?dist/(dur/60):0,avgHr:hrs.length?hrs.reduce((a,b)=>a+b,0)/hrs.length:0,maxHr:hrs.length?Math.max(...hrs):0,calories:lapStages.reduce((s,x)=>s+n(x.calories),0),elevationM:0,cadenceAvg:0,externalId:fileName,executedStages:lapStages,executedStagesJson:JSON.stringify(lapStages),originalData:JSON.stringify({fileName,laps:lapStages.length,points:pts.length})};a.fingerprint=trainingFingerprint(a);return[validateActivity(a)]
  }

  parseFitActivities=parseFitCloud;
  parseTrackXml=parseTrackCloud;

  previewTrainImport=async function(file){const source=document.getElementById('trainImportSource')?.value||state.trainImportSource;state.trainImportSource=source;const ext=(file.name.split('.').pop()||'').toLowerCase(),box=document.getElementById('trainImportPreview'),btn=document.getElementById('confirmTrainImport');try{let activities=[];if(ext==='csv')activities=csvRows(await file.text()).map(o=>validateActivity(normalizeImportedActivity(o,source)));else if(ext==='json'){const data=JSON.parse(await file.text());const arr=Array.isArray(data)?data:(data.activities||data.data||[]);activities=arr.map(o=>validateActivity(normalizeImportedActivity(o,source)))}else if(ext==='gpx'||ext==='tcx')activities=parseTrackCloud(await file.text(),source,file.name);else if(ext==='fit')activities=parseFitCloud(await file.arrayBuffer(),source,file.name);else throw new Error('Formato não suportado');activities.forEach(a=>{const forced=state.trainExecuteTarget&&trainingRows().find(t=>String(t.id)===String(state.trainExecuteTarget));const m=forced||suggestedTraining(a);a.suggestedTrainingId=m?.id||'';a.matchReason=m?(forced?'selecionado pelo botão Executar':'mesma data e modalidade compatível'):'';a.duplicateStatus=isImportedDuplicate(a)?'possivel':'novo'});pendingTrainImport={file,source,format:ext.toUpperCase(),activities,manual:false};box.innerHTML=`<strong>${esc(file.name)}</strong><p>${activities.length} atividade(s) detectada(s).</p><div class="import-mini-list">${activities.slice(0,8).map(a=>`<span>${brDate(a.date)} • ${esc(a.workoutName||a.modality)} • ${durationText(a.executedDurationMin)}${a.executedDistanceKm?` • ${fmt(a.executedDistanceKm)} km`:''}${a.executedStages?.length?` • ${a.executedStages.length} etapas`:''}${a.validationStatus==='revisar'?` • REVISAR: ${esc(a.validationWarnings)}`:''}</span>`).join('')}</div>`;btn.disabled=activities.length===0}catch(e){pendingTrainImport=null;box.innerHTML=`<span class="muted">Não foi possível ler: ${esc(e.message)}</span>`;btn.disabled=true}}

  confirmTrainImport=async function(){if(!pendingTrainImport)return;const {file,source,format,activities}=pendingTrainImport,impHeaders=rows(FILES.training,'Importacoes')[0]?.map(String)||[],imps=trainingImportRows(),now=new Date().toISOString(),importId='imp-'+Date.now(),dups=activities.filter(a=>a.duplicateStatus==='possivel').length;imps.push({id:importId,date:today(),source,fileName:file.name,format,activityCount:activities.length,status:'aguardando revisão',notes:'Importação unificada AF+ 13',importedAt:now,periodStart:activities[0]?.date||'',periodEnd:activities.at(-1)?.date||'',duplicatesDetected:dups,pendingReview:activities.length});await saveSheet(FILES.training,'Importacoes',toRows(imps,impHeaders));const raw=rows(FILES.training,'Importacao_Atividades'),h=(raw[0]||[]).map(String),all=trainingImportInboxRows();for(const f of ['workoutName','executedStagesJson','validationStatus','validationWarnings','avgSpeedKmh','totalTimeMin','activeTimeMin'])if(!h.includes(f))h.push(f);activities.forEach(a=>all.push({id:a.id,importId,date:a.date,source,fileName:file.name,format,modality:a.modality,workoutName:a.workoutName,executedDurationMin:a.executedDurationMin,executedDistanceKm:a.executedDistanceKm,executedPaceMinKm:a.executedPaceMinKm,avgHr:a.avgHr,maxHr:a.maxHr,calories:a.calories,elevationM:a.elevationM,cadenceAvg:a.cadenceAvg,avgSpeedKmh:a.avgSpeedKmh,totalTimeMin:a.totalTimeMin,activeTimeMin:a.activeTimeMin,externalId:a.externalId,fingerprint:a.fingerprint,suggestedTrainingId:a.suggestedTrainingId,matchReason:a.matchReason,duplicateStatus:a.duplicateStatus,reviewStatus:'pendente',executedStagesJson:a.executedStagesJson||'[]',validationStatus:a.validationStatus,validationWarnings:a.validationWarnings,originalData:a.originalData,createdAt:now}));await saveSheet(FILES.training,'Importacao_Atividades',toRows(all,h));pendingTrainImport=null;toast('Atividade enviada para revisão');render()}

  const baseReview=reviewImportedActivity;
  reviewImportedActivity=async function(id,mode){
    if(mode==='ignore')return baseReview(id,mode);
    const inbox=trainingImportInboxRows(),item=inbox.find(x=>String(x.id||'')===String(id));if(!item)return;
    const targetId=(mode==='link'?(item.suggestedTrainingId||state.trainExecuteTarget):'');
    await baseReview(id,mode);
    const target=targetId?trainingRows().find(x=>String(x.id)===String(targetId)):trainingRows().filter(x=>String(x.fingerprint||'')===String(item.fingerprint||'')).at(-1);if(!target)return;
    let stages=[];try{stages=JSON.parse(item.executedStagesJson||'[]')}catch(_){stages=[]}if(!Array.isArray(stages)||!stages.length)return;
    const raw=rows(FILES.training,'Blocos'),headers=(raw[0]||[]).map(String),all=trainingBlockRows(),existing=all.filter(b=>String(b.trainingId)===String(target.id)).sort((a,b)=>n(a.order)-n(b.order));
    stages.forEach((s,i)=>{let b=existing[i];if(!b){b={id:`blk-${target.id}-exec-${i+1}`,trainingId:target.id,order:i+1,type:s.type||'Etapa',source:item.source,notes:'Etapa importada da atividade'};all.push(b)}Object.assign(b,{executedDurationMin:n(s.executedDurationMin),executedDistanceKm:n(s.executedDistanceKm),executedPaceMinKm:n(s.executedPaceMinKm),avgHr:n(s.avgHr),source:item.source,notes:[b.notes,`Executado: ${item.source}`].filter(Boolean).join(' • ')})});
    await saveSheet(FILES.training,'Blocos',toRows(all,headers));state.trainExecuteTarget='';toast(`${stages.length} etapa(s) executada(s) vinculada(s)`);render();
  }

  function executeChoice(id){const pending=trainingImportInboxRows().filter(x=>String(x.reviewStatus||'pendente')==='pendente');state.modal=`<div class="modalhead"><div><h3>Executar treino</h3><div class="muted">Escolha como registrar a atividade realizada.</div></div><button class="x" data-close>×</button></div><div class="execute-choice"><button class="btn primary" id="execImport">Importar Garmin / Zepp / Strava</button><button class="btn" id="execManual">Registrar manualmente</button>${pending.length?`<button class="btn" id="execExisting">Usar atividade já importada (${pending.length})</button>`:''}</div><div id="execExistingList"></div>`;render();setTimeout(()=>{document.getElementById('execManual')?.addEventListener('click',()=>{trainingModal(id);setTimeout(()=>{const st=document.getElementById('trStatus');if(st)st.value='executado'},20)});document.getElementById('execImport')?.addEventListener('click',()=>{state.trainExecuteTarget=id;state.modal=null;state.trainTab='imports';render();setTimeout(()=>document.getElementById('trainImportFile')?.click(),100)});document.getElementById('execExisting')?.addEventListener('click',()=>{const box=document.getElementById('execExistingList');if(box)box.innerHTML=pending.map(a=>`<button class="btn exec-existing-item" data-aid="${esc(a.id)}">${brDate(a.date)} • ${esc(a.workoutName||a.modality)} • ${durationText(a.executedDurationMin)}${n(a.executedDistanceKm)?` • ${fmt(a.executedDistanceKm)} km`:''}</button>`).join('');document.querySelectorAll('.exec-existing-item').forEach(b=>b.onclick=async()=>{const a=inbox.find(x=>String(x.id)===String(b.dataset.aid));if(a)a.suggestedTrainingId=id;state.trainExecuteTarget=id;await reviewImportedActivity(b.dataset.aid,'link')})})},30)}
  const nativeSaveSheet=saveSheet;
  const QUEUE_KEY='afplus_cloud_save_queue_v13';
  function getQueue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]')}catch(_){return[]}}
  function setQueue(q){localStorage.setItem(QUEUE_KEY,JSON.stringify(q.slice(-100)))}
  saveSheet=async function(file,sheet,rowsData){
    try{return await nativeSaveSheet(file,sheet,rowsData)}catch(err){
      const q=getQueue();q.push({file,sheet,rows:rowsData,queuedAt:new Date().toISOString()});setQueue(q);
      state.books[file]=state.books[file]||{};state.books[file][sheet]=rowsData;
      toast('Sem conexão: alteração guardada para sincronizar');cloudBadge();return {ok:true,queued:true};
    }
  };
  async function flushQueue(){if(!navigator.onLine)return;let q=getQueue();if(!q.length)return;const left=[];for(const item of q){try{const r=await fetch('/api/save-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file:item.file,sheet:item.sheet,rows:item.rows})});if(!r.ok)throw new Error(await r.text())}catch(_){left.push(item)}}setQueue(left);if(q.length!==left.length)toast(`${q.length-left.length} alteração(ões) sincronizada(s)`);cloudBadge()}
  window.addEventListener('online',()=>flushQueue());setTimeout(flushQueue,1500);
  const prevBind=bind;bind=function(){prevBind();document.querySelectorAll('[data-train-execute]').forEach(b=>b.onclick=()=>executeChoice(b.dataset.trainExecute));};

  function cloudBadge(){let e=document.getElementById('afCloudBadge');if(!e){e=document.createElement('div');e.id='afCloudBadge';e.style.cssText='position:fixed;right:14px;bottom:14px;z-index:9999;background:#fff;border:1px solid #dfe3ec;border-radius:999px;padding:8px 12px;font:12px system-ui;box-shadow:0 4px 18px #0002';document.body.appendChild(e)}const q=getQueue().length;e.textContent=navigator.onLine?(q?`Google Sheets • ${q} pendente(s)`:'Google Sheets • sincronizado'):`Offline • ${q} pendente(s)`}
  window.addEventListener('online',cloudBadge);window.addEventListener('offline',cloudBadge);setTimeout(cloudBadge,300);
  document.title='AF+ 13.0 — Netlify + Google Sheets';
  console.info('[AF+ 13.0.0] Cloud runtime ativo: Sheets + Netlify + Garmin/Zepp/Strava unificados');
})();
