/* AF+ v3.0 — fechamento dos módulos Nutrição, Treinos e Corpo */
Object.assign(state,{
  nutEvoMetric:'kcal',nutEvoPeriod:'30',
  bodyWeightPeriod:'90',bodyEvoMetric:'weight',bodyEvoPeriod:'180',
  trainTemplateFilter:'all'
});

function isoDaysAgo(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-days);return isoFromDate(d)}
function inPeriod(date,period){if(period==='all')return true;return String(date||'')>=isoDaysAgo(Number(period)||30)}
function avg(vals){const v=vals.filter(x=>Number.isFinite(num(x)));return v.length?v.reduce((a,b)=>a+num(b),0)/v.length:0}
function simpleLineChart(points,unit=''){
  const clean=points.filter(x=>x&&x.date&&Number.isFinite(num(x.value)));
  if(clean.length<2)return '<div class="chart-empty">Ainda não há dados suficientes para gráfico.</div>';
  const w=760,h=220,p=28,vals=clean.map(x=>num(x.value)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;
  const xy=clean.map((x,i)=>({x:p+(i*(w-2*p)/Math.max(1,clean.length-1)),y:h-p-((num(x.value)-min)/span)*(h-2*p),...x}));
  const poly=xy.map(x=>`${x.x.toFixed(1)},${x.y.toFixed(1)}`).join(' ');
  return `<div class="mini-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Gráfico de evolução"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" class="chart-axis"/><polyline points="${poly}" class="chart-line" fill="none"/>${xy.map((x,i)=>`<circle cx="${x.x}" cy="${x.y}" r="4" class="chart-dot"><title>${brDate(x.date)} • ${fmt(x.value)}${unit}</title></circle>${(i===0||i===xy.length-1)?`<text x="${x.x}" y="${Math.max(14,x.y-10)}" text-anchor="middle" class="chart-label">${fmt(x.value)}${unit}</text>`:''}`).join('')}</svg><div class="chart-caption"><span>${brDate(clean[0].date)}</span><span>${brDate(clean.at(-1).date)}</span></div></div>`
}

/* NUTRIÇÃO */
function nutritionAudit(){
  const foods=foodRows(), byName={};foods.forEach(f=>{const k=foodName(f).trim().toLowerCase();if(k)(byName[k]??=[]).push(f)});
  const duplicates=Object.values(byName).filter(x=>x.length>1).length;
  const missing=foods.filter(f=>num(f.kcal)===0&&num(f.proteinG)===0&&num(f.carbsG)===0&&num(f.fatG)===0).length;
  const noFiber=foods.filter(f=>num(f.fiberG)===0).length;
  return {duplicates,missing,noFiber,total:foods.length}
}

const _foodsTabBase=foodsTab;
foodsTab=function(){
  const all=foodRows();const cats=[...new Set(all.map(f=>f.category).filter(Boolean))].sort();const q=state.foodSearch.trim().toLowerCase();
  let list=all.filter(f=>(state.foodCategory==='all'||String(f.category)===state.foodCategory)&&(!q||`${foodName(f)} ${f.brand||''} ${f.category||''}`.toLowerCase().includes(q)));
  list.sort((a,b)=>Number(Boolean(b.favorite))-Number(Boolean(a.favorite))||num(b.usageCount)-num(a.usageCount)||foodName(a).localeCompare(foodName(b),'pt-BR'));
  const audit=nutritionAudit();
  return `<div class="audit-strip"><div><span>Base alimentar</span><strong>${audit.total}</strong><small>alimentos</small></div><div class="${audit.missing?'warn':''}"><span>Sem dados nutricionais</span><strong>${audit.missing}</strong><small>revisar</small></div><div class="${audit.duplicates?'warn':''}"><span>Possíveis duplicados</span><strong>${audit.duplicates}</strong><small>nomes repetidos</small></div><div><span>Favoritos</span><strong>${all.filter(x=>x.favorite===true||String(x.favorite)==='true').length}</strong><small>atalhos</small></div></div>
  <div class="foodtoolbar"><div><h3>Alimentos</h3><span class="muted">${list.length} de ${all.length} alimentos</span></div><div class="foodfilters"><input id="foodSearch" placeholder="Buscar alimento" value="${esc(state.foodSearch)}"><select id="foodCategory"><option value="all">Todas as categorias</option>${cats.map(c=>`<option ${state.foodCategory===c?'selected':''}>${esc(c)}</option>`).join('')}</select><button class="btn primary" id="addFoodMaster">+ Adicionar alimento</button></div></div>
  <div class="foodcards">${list.map(f=>`<article class="foodcard ${f.favorite===true||String(f.favorite)==='true'?'favorite':''}"><div class="foodcardtop"><div><div class="food-title-row"><h3>${esc(foodName(f))}</h3><button class="starbtn" data-food-favorite="${esc(foodId(f))}" title="Favorito">${f.favorite===true||String(f.favorite)==='true'?'★':'☆'}</button></div><span class="muted">${esc([f.brand,f.category].filter(Boolean).join(' • '))}</span></div><button class="btn" data-edit-food="${esc(foodId(f))}">Editar</button></div><div class="foodportion">Porção base: <strong>${fmt(f.portion)} ${esc(f.unit||'')}</strong>${num(f.usageCount)?`<span class="muted"> • usado ${fmt(f.usageCount)}x</span>`:''}</div><div class="foodnutri"><span><strong>${fmt(f.kcal)}</strong> kcal</span><span><strong>${fmt(f.proteinG)}</strong> g proteína</span><span><strong>${fmt(f.carbsG)}</strong> g carbo</span><span><strong>${fmt(f.fatG)}</strong> g gordura</span><span><strong>${fmt(f.fiberG)}</strong> g fibra</span><span><strong>${fmt(f.sugarG)}</strong> g açúcar</span></div></article>`).join('')||'<div class="card empty">Nenhum alimento encontrado.</div>'}</div>`
};
async function toggleFoodFavorite(id){const headers=rows(FILES.nutrition,'Alimentos')[0].map(String),objs=foodRows(),f=objs.find(x=>String(foodId(x))===String(id));if(!f)return;f.favorite=!(f.favorite===true||String(f.favorite)==='true');await saveSheet(FILES.nutrition,'Alimentos',toRows(objs,headers));render()}
async function markFoodsUsed(items){const headers=rows(FILES.nutrition,'Alimentos')[0].map(String),objs=foodRows(),now=new Date().toISOString();let changed=false;items.forEach(it=>{const f=objs.find(x=>String(foodId(x))===String(it.foodId||''))||objs.find(x=>foodName(x).toLowerCase()===String(it.name||'').toLowerCase());if(f){f.lastUsedAt=now;f.usageCount=num(f.usageCount)+1;changed=true}});if(changed)await saveSheet(FILES.nutrition,'Alimentos',toRows(objs,headers))}
const _writeConsumptionBase=writeConsumption;
writeConsumption=async function(payload){await _writeConsumptionBase(payload);await markFoodsUsed(payload.items||[])};

function plannedTotalsForDay(dayIndex){return mealNames().reduce((a,m)=>{const p=pickPlan(dayIndex,m);if(p){a.kcal+=num(p.plannedKcal);a.protein+=num(p.plannedProteinG);a.carbs+=num(p.plannedCarbsG);a.fat+=num(p.plannedFatG);a.fiber+=num(p.plannedFiberG);a.sugar+=num(p.plannedSugarG)}return a},{kcal:0,protein:0,carbs:0,fat:0,fiber:0,sugar:0})}
const _nutTodayBase=nutToday;
nutToday=function(){const d=new Date().getDay(),pt=plannedTotalsForDay(d),ct=todayNutritionTotals(),y=dateOffset(-1),yg=gastoForDate(y);return `<div class="day-balance"><div><span>Planejado hoje</span><strong>${fmt(pt.kcal)} kcal</strong><small>${fmt(pt.protein)} g proteína • ${fmt(pt.carbs)} g carbo</small></div><div><span>Consumido até agora</span><strong>${fmt(ct.kcal)} kcal</strong><small>${fmt(ct.protein)} g proteína • ${fmt(ct.fiber)} g fibra</small></div><div><span>Diferença do plano</span><strong>${ct.kcal-pt.kcal>0?'+':''}${fmt(ct.kcal-pt.kcal)} kcal</strong><small>consumido − planejado</small></div><div><span>Ontem</span><strong>${yg?deficitLabel(yg):'Aguardando gasto'}</strong><small>fechamento pelo relógio</small></div></div>${_nutTodayBase()}`}

const _nutWeekBase=nutWeek;
nutWeek=function(){return `<div class="module-actions"><button class="btn" id="copyNutDay">Copiar dia selecionado</button><button class="btn" id="clearNutDay">Limpar planejamento do dia</button><span class="muted">Dia selecionado: ${DAYS[state.day]}</span></div>${_nutWeekBase()}`}
function copyNutDayModal(){state.modal=`<div class="modalhead"><div><h3>Copiar planejamento de ${DAYS[state.day]}</h3><div class="muted">Copia todas as refeições e itens montados para outro dia.</div></div><button class="x" data-close>×</button></div><div class="field"><label>Destino</label><select id="copyNutTarget">${DAYS.map((d,i)=>i===state.day?'':`<option value="${i}">${d}</option>`).join('')}</select></div><div class="actions" style="margin-top:14px"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="confirmCopyNutDay">Copiar</button></div>`;render()}
async function copyNutDay(){const target=Number(document.getElementById('copyNutTarget').value),src=DAYS[state.day],dst=DAYS[target],headers=rows(FILES.nutrition,'Planejamento')[0].map(String),plans=planRows(),itemHeaders=rows(FILES.nutrition,'Planejamento_Itens')[0].map(String),items=planItemRows(),now=new Date().toISOString();const srcPlans=plans.filter(p=>String(p.day).toUpperCase()===src&&String(p.status||'planejado').toLowerCase()!=='cancelado');const dstPlans=plans.filter(p=>String(p.day).toUpperCase()===dst);dstPlans.forEach(p=>p.status='cancelado');for(const p of srcPlans){const nid='plan-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),np={...p,id:nid,day:dst,date:'',copiedFromId:p.id,updatedAt:now,createdAt:now,source:'copia',status:'planejado'};plans.push(np);items.filter(it=>String(it.planId)===String(p.id)).forEach((it,i)=>items.push({...it,id:`${nid}-item-${i+1}`,planId:nid,createdAt:now}))}await saveSheet(FILES.nutrition,'Planejamento',toRows(plans,headers));await saveSheet(FILES.nutrition,'Planejamento_Itens',toRows(items,itemHeaders));state.modal=null;state.day=target;render()}
async function clearNutDay(){if(!confirm(`Limpar o planejamento de ${DAYS[state.day]}?`))return;const headers=rows(FILES.nutrition,'Planejamento')[0].map(String),plans=planRows();plans.forEach(p=>{if(String(p.day).toUpperCase()===DAYS[state.day])p.status='cancelado'});await saveSheet(FILES.nutrition,'Planejamento',toRows(plans,headers));render()}

nutHistory=function(){const all=consumptionRows().slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.createdAt).localeCompare(String(a.createdAt)));if(!all.length)return '<div class="card empty">Nenhum consumo registrado.</div>';const dates=[...new Set(all.map(x=>x.date))];return `<div class="sectiontitle"><h3>Histórico</h3><span class="muted">Planejado × realmente consumido</span></div><div class="history-days">${dates.map(d=>{const cs=all.filter(x=>x.date===d),tot=nutritionTotalsForDate(d),water=waterRows().filter(x=>x.date===d).reduce((s,x)=>s+num(x.ml),0),g=gastoForDate(d);return `<article class="history-day"><div class="history-day-head"><div><span class="body-kicker">${brDate(d)}</span><h3>${fmt(tot.kcal)} kcal</h3></div><div class="train-stats"><span>${fmt(tot.protein)} g proteína</span><span>${fmt(tot.fiber)} g fibra</span><span>${fmt(water)} ml água</span>${g?`<span>${deficitLabel(g)}</span>`:''}</div></div>${cs.map(c=>{const p=planRows().find(x=>String(x.id)===String(c.sourcePlanId)),its=consumptionItemRows().filter(x=>String(x.consumptionId)===String(c.id));return `<div class="history-meal"><div><strong>${esc(c.meal)}</strong><small>${esc(c.name||'Consumo')}</small></div><div><span class="muted">Planejado</span><strong>${p?`${esc(p.name)} • ${fmt(p.plannedKcal)} kcal`:'Sem planejamento'}</strong></div><div><span class="muted">Consumido</span><strong>${fmt(c.kcal)} kcal</strong><small>${its.map(i=>`${esc(i.foodName)} ${fmt(i.quantity)} ${esc(i.unit)}`).join(' • ')}</small></div></div>`}).join('')}</article>`}).join('')}</div>`}

function nutMetricForDate(date,metric){if(metric==='water')return waterRows().filter(x=>x.date===date).reduce((s,x)=>s+num(x.ml),0);if(metric==='deficit'){const g=gastoForDate(date);return g?num(g.deficit_kcal):0}const t=nutritionTotalsForDate(date);return num(t[metric])}
nutEvo=function(){const metricMap={kcal:['Calorias',' kcal'],protein:['Proteína',' g'],carbs:['Carboidratos',' g'],fiber:['Fibra',' g'],sugar:['Açúcar',' g'],water:['Água',' ml'],deficit:['Déficit',' kcal']};const dates=[...new Set([...consumptionRows().map(x=>x.date),...waterRows().map(x=>x.date),...gastoRows().map(x=>x.data_referencia||x.date)].filter(Boolean))].filter(d=>inPeriod(d,state.nutEvoPeriod)).sort();const pts=dates.map(date=>({date,value:nutMetricForDate(date,state.nutEvoMetric)}));const vals=pts.map(x=>x.value),m=metricMap[state.nutEvoMetric]||metricMap.kcal;return `<div class="train-toolbar"><div><h3>Evolução nutricional</h3><span class="muted">Consumo real registrado</span></div><div><select id="nutEvoMetric">${Object.entries(metricMap).map(([k,v])=>`<option value="${k}" ${state.nutEvoMetric===k?'selected':''}>${v[0]}</option>`).join('')}</select><select id="nutEvoPeriod"><option value="30" ${state.nutEvoPeriod==='30'?'selected':''}>30 dias</option><option value="90" ${state.nutEvoPeriod==='90'?'selected':''}>3 meses</option><option value="180" ${state.nutEvoPeriod==='180'?'selected':''}>6 meses</option><option value="365" ${state.nutEvoPeriod==='365'?'selected':''}>1 ano</option><option value="all" ${state.nutEvoPeriod==='all'?'selected':''}>Tudo</option></select></div></div><div class="grid"><div class="card"><h3>Média</h3><div class="metric">${fmt(avg(vals))}${m[1]}</div></div><div class="card"><h3>Último registro</h3><div class="metric">${pts.length?fmt(pts.at(-1).value)+m[1]:'—'}</div></div><div class="card"><h3>Registros</h3><div class="metric">${pts.length}</div></div><div class="card"><h3>Meta atual</h3><div class="metric">${state.nutEvoMetric==='kcal'?fmt(goalValue('kcalGoal'))+' kcal':state.nutEvoMetric==='protein'?fmt(goalValue('proteinGGoal'))+' g':state.nutEvoMetric==='carbs'?fmt(goalValue('carbsGGoal'))+' g':state.nutEvoMetric==='fiber'?fmt(goalValue('fiberGGoal'))+' g':state.nutEvoMetric==='sugar'?fmt(goalValue('sugarGGoal'))+' g':state.nutEvoMetric==='water'?fmt(goalValue('waterMl'))+' ml':'—'}</div></div></div><div class="card chart-card">${simpleLineChart(pts,m[1])}</div>`}

/* TREINOS */
function trainingTemplateRows(){return objRows(FILES.training,'Modelos')}
const _parseTreinusTextBase=parseTreinusText;
parseTreinusText=function(text){return _parseTreinusTextBase(text).map(b=>{if(String(b.type).toLowerCase().includes('caminh')&&!num(b.plannedPaceMinKm)){b.plannedPaceMinKm=10.433;b.plannedPaceMaxMinKm=12.5;const min=num(b.plannedDurationMin)/12.5,max=num(b.plannedDurationMin)/10.433;b.plannedDistanceMinKm=min;b.plannedDistanceMaxKm=max;b.plannedSpeedMinKmh=4.8;b.plannedSpeedMaxKmh=5.75}return b})}

treinusPreviewHtml=function(blocks){if(!blocks.length)return '<div class="card empty">Nenhuma etapa reconhecida. Confira o texto colado.</div>';const total=blocks.reduce((a,b)=>{a.min+=num(b.plannedDurationMin);a.dmin+=num(b.plannedDistanceMinKm||b.plannedDistanceKm);a.dmax+=num(b.plannedDistanceMaxKm||b.plannedDistanceKm);a.walk+=String(b.type).toLowerCase().includes('caminh')?num(b.plannedDurationMin):0;a.z2+=String(b.zone).toUpperCase()==='Z2'?num(b.plannedDurationMin):0;a.z3+=String(b.zone).toUpperCase()==='Z3'?num(b.plannedDurationMin):0;return a},{min:0,dmin:0,dmax:0,walk:0,z2:0,z3:0});return `<div class="parser-summary"><span><strong>${durationText(total.min)}</strong> total</span><span><strong>${fmt(total.dmin)}–${fmt(total.dmax)} km</strong> estimados</span><span><strong>${durationText(total.z2)}</strong> Z2</span><span><strong>${durationText(total.z3)}</strong> Z3</span><span><strong>${durationText(total.walk)}</strong> caminhada</span></div><div class="treinus-flow">${blocks.map((b,i)=>`<div class="flow-chip ${String(b.type).toLowerCase().includes('caminh')?'walk':''}"><strong>${i+1}. ${esc(b.type)}${b.zone?' '+esc(b.zone):''}</strong><span>${durationText(b.plannedDurationMin)}${b.repeatCount?` • ${b.repeatIndex}/${b.repeatCount}`:''}</span></div>`).join('<span class="flow-arrow">→</span>')}</div><div class="treinus-paste-preview">${blocks.map((b,i)=>`<div class="treinus-preview-edit" data-preview-index="${i}"><span class="block-order">${i+1}</span><select data-p-type><option ${b.type==='Corrida'?'selected':''}>Corrida</option><option ${b.type==='Caminhada'?'selected':''}>Caminhada</option><option ${b.type==='Aquecimento'?'selected':''}>Aquecimento</option><option ${b.type==='Recuperação'?'selected':''}>Recuperação</option><option ${b.type==='Desaquecimento'?'selected':''}>Desaquecimento</option></select><input data-p-min type="number" step="0.1" value="${esc(b.plannedDurationMin)}" title="minutos"><input data-p-zone value="${esc(b.zone||'')}" placeholder="Zona"><input data-p-pace1 type="number" step="0.01" value="${esc(b.plannedPaceMinKm||'')}" placeholder="ritmo mín"><input data-p-pace2 type="number" step="0.01" value="${esc(b.plannedPaceMaxMinKm||'')}" placeholder="ritmo máx"><input data-p-dmin type="number" step="0.01" value="${esc(b.plannedDistanceMinKm||'')}" placeholder="km mín"><input data-p-dmax type="number" step="0.01" value="${esc(b.plannedDistanceMaxKm||'')}" placeholder="km máx"><input data-p-repeat type="number" min="1" value="${esc(b.repeatCount||1)}" title="repetições"></div>`).join('')}</div>`}
const _applyTreinusParsedBase=applyTreinusParsed;
applyTreinusParsed=function(){document.querySelectorAll('.treinus-preview-edit').forEach(row=>{const i=Number(row.dataset.previewIndex),b=pendingTreinusParsed[i];if(!b)return;b.type=row.querySelector('[data-p-type]').value;b.plannedDurationMin=num(row.querySelector('[data-p-min]').value);b.zone=row.querySelector('[data-p-zone]').value.trim();b.plannedPaceMinKm=num(row.querySelector('[data-p-pace1]').value);b.plannedPaceMaxMinKm=num(row.querySelector('[data-p-pace2]').value);b.plannedDistanceMinKm=num(row.querySelector('[data-p-dmin]').value);b.plannedDistanceMaxKm=num(row.querySelector('[data-p-dmax]').value);b.repeatCount=Math.max(1,num(row.querySelector('[data-p-repeat]').value)||1)});_applyTreinusParsedBase()}

function trainToday(){const list=trainingForDate(today());if(!list.length)return `<div class="card empty"><h3>Nenhum treino para hoje</h3><p>Você pode adicionar um treino na Semana.</p><button class="btn primary" data-train-new="${today()}">+ Planejar treino</button></div>`;return `<div class="sectiontitle"><h3>Treino de hoje</h3><span class="muted">${brDate(today())}</span></div><div class="today-training-list">${list.map(x=>{const blocks=trainingBlocks(x.id);return `<article class="today-training-card"><div class="body-card-head"><div><span class="body-kicker">${esc(trainModality(x))} • ${esc(x.source||'Manual')}</span><h3>${esc(x.workoutName||trainModality(x))}</h3><small>${esc(x.objective||'')}</small></div><span class="pill ${trainStatus(x)==='executado'?'done':''}">${esc(x.status)}</span></div>${plannedExecutedSummary(x)}${blocks.length?`<div class="today-blocks">${blocks.map((b,i)=>`<div class="today-block ${String(b.type).toLowerCase().includes('caminh')?'walk':''}"><span>${i+1}</span><div><strong>${esc(b.type)}${b.zone?' • '+esc(b.zone):''}</strong><small>${durationText(b.plannedDurationMin)} • ${num(b.plannedPaceMinKm)?paceText(b.plannedPaceMinKm)+(num(b.plannedPaceMaxMinKm)?' – '+paceText(b.plannedPaceMaxMinKm):''):''}</small></div><div><strong>${num(b.plannedSpeedMinKmh)?fmt(b.plannedSpeedMinKmh)+'–'+fmt(b.plannedSpeedMaxKmh)+' km/h':'—'}</strong><small>esteira</small></div></div>`).join('')}</div>`:''}<div class="actions"><button class="btn" data-train-edit="${esc(x.id)}">Ver / registrar execução</button></div></article>`}).join('')}</div>`}

const _trainingBase=training;
training=function(){const defs=[['today','Hoje'],['week','Semana'],['history','Histórico'],['run','Corrida'],['activities','Atividades'],['evo','Evolução'],['templates','Modelos'],['imports','Importações']];let c=hero('TREINOS','Planejado → executado → histórico, com Treinus por etapas e importação por arquivo.')+tabs(defs,state.trainTab,'data-ttab');if(state.trainTab==='today')c+=trainToday();if(state.trainTab==='week')c+=trainWeek();if(state.trainTab==='history')c+=trainHistory();if(state.trainTab==='run')c+=trainRun();if(state.trainTab==='activities')c+=trainActivities();if(state.trainTab==='evo')c+=trainEvolution();if(state.trainTab==='templates')c+=trainTemplates();if(state.trainTab==='imports')c+=trainImports();return shell(c,'Treinos')}

const _trainWeekBase=trainWeek;
trainWeek=function(){return `<div class="module-actions"><button class="btn" id="duplicateTrainWeek">Duplicar semana para a próxima</button><button class="btn" id="exportTrainCsv">Exportar histórico CSV</button></div>${_trainWeekBase()}`}
const _trainWeekSummaryBase=trainWeekSummary;
trainWeekSummary=function(dates){const rr=trainingRows().filter(x=>dates.includes(String(x.date||''))),done=rr.filter(x=>trainStatus(x)==='executado');const mods=['Corrida','Academia','Pilates'];return `${_trainWeekSummaryBase(dates)}<div class="activity-grid" style="margin-top:12px">${mods.map(m=>{const a=done.filter(x=>trainModality(x).toLowerCase()===m.toLowerCase());return `<div class="activity-card"><span>${m}</span><strong>${a.length}</strong><small>${durationText(a.reduce((s,x)=>s+num(x.executedDurationMin),0))}${m==='Corrida'?` • ${fmt(a.reduce((s,x)=>s+num(x.executedDistanceKm),0))} km`:''}</small></div>`}).join('')}</div>`}

runBlockCards=function(trainingId){const list=trainingBlocks(trainingId);if(!list.length)return '';return `<div class="run-blocks"><h4>Etapas do treino — planejado × executado</h4>${list.map((b,i)=>{const dt=num(b.executedDurationMin)&&num(b.plannedDurationMin)?num(b.executedDurationMin)-num(b.plannedDurationMin):null,dd=num(b.executedDistanceKm)&&num(b.plannedDistanceKm)?num(b.executedDistanceKm)-num(b.plannedDistanceKm):null;return `<div class="run-block-comparison"><div><strong>${i+1}. ${esc(b.type||'Etapa')}${b.zone?' • '+esc(b.zone):''}</strong><small>${esc(b.intensity||b.notes||'')}</small></div><div><span>Planejado</span><strong>${durationText(b.plannedDurationMin)}</strong><small>${num(b.plannedDistanceMinKm)?fmt(b.plannedDistanceMinKm)+(num(b.plannedDistanceMaxKm)?'–'+fmt(b.plannedDistanceMaxKm):'')+' km':num(b.plannedDistanceKm)?fmt(b.plannedDistanceKm)+' km':'—'}${num(b.plannedPaceMinKm)?` • ${paceText(b.plannedPaceMinKm)}`:''}</small></div><div><span>Executado</span><strong>${num(b.executedDurationMin)?durationText(b.executedDurationMin):'—'}</strong><small>${num(b.executedDistanceKm)?fmt(b.executedDistanceKm)+' km':''}${num(b.executedPaceMinKm)?` • ${paceText(b.executedPaceMinKm)}`:''}${num(b.avgHr)?` • FC ${fmt(b.avgHr)}`:''}</small>${dt!==null?`<small class="delta-note">Δ tempo ${dt>0?'+':''}${fmt(dt)} min${dd!==null?` • Δ dist. ${dd>0?'+':''}${fmt(dd)} km`:''}</small>`:''}</div></div>`}).join('')}</div>`}

function trainTemplates(){const t=trainingTemplateRows();return `<div class="train-toolbar"><div><h3>Modelos de treino</h3><span class="muted">Salve treinos estruturados para reutilizar.</span></div></div><div class="run-cards">${t.map(x=>`<article class="run-card"><div class="body-card-head"><div><span class="body-kicker">${esc(x.modality||'Treino')}</span><h3>${esc(x.name)}</h3><small>${esc(x.objective||'')}</small></div><span class="pill">Modelo</span></div><div class="train-stats"><span>${(()=>{try{return JSON.parse(x.blocksJson||'[]').length}catch(e){return 0}})()} etapas</span></div><div class="actions"><button class="btn primary" data-use-template="${esc(x.id)}">Usar modelo</button></div></article>`).join('')||'<div class="card empty">Nenhum modelo salvo. No Histórico, use “Salvar como modelo”.</div>'}</div>`}
async function saveTrainingAsTemplate(id){const x=trainingRows().find(t=>String(t.id)===String(id));if(!x)return;const headers=rows(FILES.training,'Modelos')[0].map(String),all=trainingTemplateRows(),now=new Date().toISOString();all.push({id:'tpl-'+Date.now(),name:x.workoutName||trainModality(x),modality:trainModality(x),objective:x.objective||'',blocksJson:JSON.stringify(trainingBlocks(id)),favorite:true,createdAt:now,updatedAt:now});await saveSheet(FILES.training,'Modelos',toRows(all,headers));toast('Modelo salvo');}
function useTrainingTemplate(id){const t=trainingTemplateRows().find(x=>String(x.id)===String(id));if(!t)return;trainingModal('',{date:today(),modality:t.modality||'Corrida',status:'planejado'});setTimeout(()=>{const n=document.getElementById('trWorkoutName'),o=document.getElementById('trObjective'),box=document.getElementById('treinusBlocks');if(n)n.value=t.name||'';if(o)o.value=t.objective||'';let bs=[];try{bs=JSON.parse(t.blocksJson||'[]')}catch(e){}if(box&&bs.length){box.innerHTML='';bs.forEach(b=>addTrainBlockRow(b));const min=bs.reduce((s,b)=>s+num(b.plannedDurationMin),0);const dist=bs.reduce((s,b)=>s+num(b.plannedDistanceKm||b.plannedDistanceMinKm),0);if(document.getElementById('trPlannedDuration'))document.getElementById('trPlannedDuration').value=min||'';if(document.getElementById('trPlannedDistance'))document.getElementById('trPlannedDistance').value=dist||''}},100)}

const _trainHistoryBase=trainHistory;
trainHistory=function(){return _trainHistoryBase().replace(/<button class="btn" data-train-edit="([^"]+)">Detalhes<\/button>/g,'<button class="btn" data-save-template="$1">Salvar como modelo</button><button class="btn" data-train-edit="$1">Detalhes</button>')}
async function duplicateTrainingWeek(){const dates=weekDates(state.trainWeekOffset),next=weekDates(state.trainWeekOffset+1),headers=rows(FILES.training,'Treinos')[0].map(String),all=trainingRows(),bHeaders=rows(FILES.training,'Blocos')[0].map(String),blocks=trainingBlockRows(),now=new Date().toISOString();let count=0;for(let i=0;i<7;i++){const src=all.filter(x=>String(x.date)===dates[i]&&trainStatus(x)!=='executado');for(const x of src){const nid='tr-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),nx={...x,id:nid,date:next[i],weekday:DAYS[i],status:'planejado',executedDurationMin:'',executedDistanceKm:'',executedPaceMinKm:'',avgHr:'',maxHr:'',calories:'',seriesId:x.seriesId||x.id,createdAt:now,updatedAt:now};all.push(nx);trainingBlocks(x.id).forEach((b,j)=>blocks.push({...b,id:`blk-${nid}-${j+1}`,trainingId:nid,executedDurationMin:'',executedDistanceKm:'',executedPaceMinKm:'',avgHr:''}));count++}}await saveSheet(FILES.training,'Treinos',toRows(all,headers));await saveSheet(FILES.training,'Blocos',toRows(blocks,bHeaders));state.trainWeekOffset++;toast(`${count} treino(s) duplicado(s)`);render()}
function downloadTrainingCsv(){const headers=['date','modality','status','source','workoutName','plannedDurationMin','executedDurationMin','plannedDistanceKm','executedDistanceKm','executedPaceMinKm','avgHr','maxHr','calories'];const lines=[headers.join(';'),...trainingRows().map(x=>headers.map(h=>String(x[h]??'').replace(/;/g,',')).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AF_PLUS_TREINOS.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

const _suggestedTrainingBase=suggestedTraining;
suggestedTraining=function(a){const c=trainingRows().filter(x=>String(x.date||'')===String(a.date||'')&&trainStatus(x)!=='executado');if(!c.length)return null;const score=x=>{let s=0;if(trainModality(x).toLowerCase().includes(String(a.modality||'').toLowerCase())||String(a.modality||'').toLowerCase().includes(trainModality(x).toLowerCase()))s+=50;const dd=Math.abs(num(x.plannedDurationMin)-num(a.executedDurationMin));if(dd<=2)s+=25;else if(dd<=5)s+=15;const dist=Math.abs(num(x.plannedDistanceKm)-num(a.executedDistanceKm));if(dist<=.25)s+=20;else if(dist<=.75)s+=10;return s};return c.slice().sort((x,y)=>score(y)-score(x))[0]||null}
isImportedDuplicate=function(a){const sameDate=trainingRows().filter(x=>String(x.date||'')===String(a.date||'')&&trainStatus(x)==='executado');return sameDate.some(x=>Math.abs(num(x.executedDurationMin)-num(a.executedDurationMin))<=2&&Math.abs(num(x.executedDistanceKm)-num(a.executedDistanceKm))<=.15&&trainModality(x).toLowerCase()===String(a.modality||'').toLowerCase())||trainingImportInboxRows().some(x=>String(x.fingerprint||'')===String(a.fingerprint||trainingFingerprint(a))&&String(x.reviewStatus||'')!=='ignorado')}

/* CORPO */
function bodyWeightRowsSorted(){return objRows(FILES.body,'Peso').slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')))}
function weightVal(x){return num(x?.weightKg||x?.weight||x?.peso)}
function latestDateBody(){return [...objRows(FILES.body,'Peso'),...objRows(FILES.body,'Medidas'),...objRows(FILES.body,'Bioimpedancia'),...objRows(FILES.body,'Adipometria')].map(x=>x.date||x.data).filter(Boolean).sort().at(-1)||''}
function latestAtOrBefore(rows,date){return rows.filter(x=>String(x.date||x.data||'')<=String(date||today())).sort((a,b)=>String(a.date||a.data||'').localeCompare(String(b.date||b.data||''))).at(-1)||null}
function bodyMetricCard(title,value,row,suffix='',source=''){const d=row?.date||row?.data||'';const sub=row?`${d?brDate(d):''}${source||row.source?` • ${esc(source||row.source||'')}`:''}`:'Sem registro até esta data';return card(title,row?`${fmt(value)}${suffix}`:'—',sub)}
bodyOverview=function(){const selected=state.bodyOverviewDate||latestDateBody()||today();const allW=bodyWeightRowsSorted(),allM=objRows(FILES.body,'Medidas'),allS=objRows(FILES.body,'Adipometria');const w=latestAtOrBefore(allW,selected),m=latestAtOrBefore(allM,selected),s=latestAtOrBefore(allS,selected);const prevW=w?allW.filter(x=>String(x.date)<String(w.date)).at(-1):null;const series=allW.filter(x=>String(x.date)<=String(selected)).slice(-12).map(x=>({date:x.date,value:weightVal(x)}));return `<div class="train-toolbar"><div><h3>Visão em uma data</h3><span class="muted">Cada indicador usa o último registro conhecido até a data escolhida.</span></div><div><input id="bodyOverviewDate" type="date" value="${esc(selected)}"></div></div><div class="grid">${bodyMetricCard('Peso',w?weightVal(w):0,w,' kg',w?.source||'Peso')}${bodyMetricCard('Cintura',m?num(m.cintura||m.cintura_cm):0,m,' cm',m?.source||'Medidas')}${bodyMetricCard('Abdômen',m?num(m.abdomen||m.abdomen_cm):0,m,' cm',m?.source||'Medidas')}${bodyMetricCard('% gordura — adipometria',s?num(s.bodyFatPct):0,s,'%',s?.source||'Nutricionista')}${bodyMetricCard('Soma das dobras',s?num(s.sumFoldsMm):0,s,' mm',s?.source||'Nutricionista')}</div>${w&&prevW?`<div class="body-last-eval"><span>Variação do peso vs registro anterior</span><strong>${weightVal(w)-weightVal(prevW)>0?'+':''}${fmt(weightVal(w)-weightVal(prevW))} kg</strong></div>`:''}<div class="card chart-card"><div class="sectiontitle"><h3>Tendência do peso</h3><span class="muted">Registros até ${brDate(selected)}</span></div>${simpleLineChart(series,' kg')}</div>`}

bodyWeightView=function(){const all=bodyWeightRowsSorted(),f=all.filter(x=>inPeriod(x.date,state.bodyWeightPeriod));if(!all.length)return '<div class="card empty">Nenhum peso registrado.</div>';const last=all.at(-1),prev=all.at(-2),vals=f.map(weightVal);return `<div class="train-toolbar"><div><h3>Peso</h3><span class="muted">Histórico e tendência</span></div><select id="bodyWeightPeriod"><option value="7" ${state.bodyWeightPeriod==='7'?'selected':''}>7 dias</option><option value="30" ${state.bodyWeightPeriod==='30'?'selected':''}>30 dias</option><option value="90" ${state.bodyWeightPeriod==='90'?'selected':''}>90 dias</option><option value="all" ${state.bodyWeightPeriod==='all'?'selected':''}>Tudo</option></select></div><div class="grid">${card('Atual',fmt(weightVal(last))+' kg',prettyDate(last.date))}${card('Em relação ao anterior',prev?`${weightVal(last)-weightVal(prev)>0?'+':''}${fmt(weightVal(last)-weightVal(prev))} kg`:'—')}${card('Mínimo no período',vals.length?fmt(Math.min(...vals))+' kg':'—')}${card('Máximo no período',vals.length?fmt(Math.max(...vals))+' kg':'—')}</div><div class="card chart-card">${simpleLineChart(f.map(x=>({date:x.date,value:weightVal(x)})),' kg')}</div><div class="body-timeline">${f.slice().reverse().map((x,i)=>`<article class="body-record"><div class="body-record-date">${prettyDate(x.date)}</div><div class="body-record-main"><strong>${fmt(weightVal(x))} kg</strong><span class="body-mini">${esc(x.source||'Manual')}</span></div></article>`).join('')}</div>`}

const _bodyMeasuresBase=bodyMeasuresView;
bodyMeasuresView=function(){const m=objRows(FILES.body,'Medidas').slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!m.length)return '<div class="card empty">Nenhuma medida registrada.</div>';const cur=m.at(-1),prev=m.at(-2);const metrics=[['Cintura','cintura'],['Abdômen','abdomen'],['Quadril','quadril'],['Tórax','torax'],['Braço D relaxado','bracoDirRelaxado'],['Coxa D','coxaDir']];return `<div class="sectiontitle"><h3>Comparação da última avaliação</h3><span class="muted">${prev?`${prettyDate(prev.date)} → ${prettyDate(cur.date)}`:'Sem avaliação anterior'}</span></div><div class="measure-compare">${metrics.map(([label,key])=>{const cv=num(cur[key]),pv=prev?num(prev[key]):0,d=prev?cv-pv:null;return `<div><span>${label}</span><strong>${fmt(cv)} cm</strong><small>${d===null?'—':`${d>0?'+':''}${fmt(d)} cm`}</small></div>`}).join('')}</div>${_bodyMeasuresBase()}`}

function bodyBioCard(x){return `<article class="body-eval-card"><div class="body-card-head"><div><span class="body-kicker">${esc(x.source||'Bioimpedância')}</span><h3>${prettyDate(x.date)}</h3><small class="muted">${esc([x.equipment,x.appSource].filter(Boolean).join(' • '))}</small></div><span class="pill">${esc(x.source||'Registro')}</span></div><div class="bio-grid">${bioMetric('Peso',x.weightKg,' kg')}${bioMetric('Gordura corporal',x.bodyFatPct||x.fatMassPct,'%')}${bioMetric('Massa de gordura',x.fatMassKg,' kg')}${bioMetric('Massa muscular',x.muscleMassKg,' kg')}${bioMetric('Massa livre de gordura',x.fatFreeMassKg,' kg')}${bioMetric('Água corporal',x.bodyWaterPct,'%')}${bioMetric('Gordura visceral',x.visceralFat,'')}${bioMetric('IMC',x.bmi,'')}${bioMetric('Metabolismo basal',x.bmrKcal,' kcal')}${bioMetric('Idade corporal',x.bodyAge,' anos')}</div></article>`}
bodyBioView=function(){const rr=objRows(FILES.body,'Bioimpedancia').slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(!rr.length)return '<div class="card empty">Nenhuma bioimpedância registrada.</div>';const groups={};rr.forEach(x=>{const k=String(x.source||'Outro');(groups[k]??=[]).push(x)});return Object.entries(groups).map(([source,list])=>`<div class="sectiontitle"><div><h3>${esc(source)}</h3><span class="muted">Comparações apenas dentro deste método/equipamento</span></div></div><div class="body-record-grid">${list.map((x,i)=>{const older=list[i+1],delta=older&&num(x.bodyFatPct||x.fatMassPct)&&num(older.bodyFatPct||older.fatMassPct)?num(x.bodyFatPct||x.fatMassPct)-num(older.bodyFatPct||older.fatMassPct):null;return bodyBioCard(x).replace('</article>',`${delta!==null?`<div class="method-delta">Δ gordura vs registro anterior do mesmo método: <strong>${delta>0?'+':''}${fmt(delta)} p.p.</strong></div>`:''}</article>`) }).join('')}</div>`).join('')}

const _bodySkinBase=bodySkinView;
bodySkinView=function(){const r=objRows(FILES.body,'Adipometria').slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))),cur=r.at(-1),prev=r.at(-2);const cmp=cur?`<div class="grid">${card('Soma atual',fmt(cur.sumFoldsMm)+' mm',prev?`${num(cur.sumFoldsMm)-num(prev.sumFoldsMm)>0?'+':''}${fmt(num(cur.sumFoldsMm)-num(prev.sumFoldsMm))} mm vs anterior`:'')}${card('% gordura',fmt(cur.bodyFatPct)+'%',prev?`${num(cur.bodyFatPct)-num(prev.bodyFatPct)>0?'+':''}${fmt(num(cur.bodyFatPct)-num(prev.bodyFatPct))} p.p. vs anterior`:'')}${card('Massa de gordura',fmt(cur.fatMassKg)+' kg')}${card('Massa livre',fmt(cur.leanMassKg)+' kg')}</div>`:'';return cmp+_bodySkinBase()}

bodyEvaluations=function(){const dates=new Set();['Peso','Medidas','Bioimpedancia','Adipometria'].forEach(sh=>objRows(FILES.body,sh).forEach(x=>dates.add(x.date||x.data)));const all=[...dates].filter(Boolean).sort().reverse();if(!all.length)return '<div class="card empty">Nenhuma avaliação registrada.</div>';return `<div class="body-record-grid">${all.map(d=>{const weight=objRows(FILES.body,'Peso').find(x=>(x.date||x.data)===d),measures=objRows(FILES.body,'Medidas').find(x=>(x.date||x.data)===d),bio=objRows(FILES.body,'Bioimpedancia').find(x=>(x.date||x.data)===d),skin=objRows(FILES.body,'Adipometria').find(x=>(x.date||x.data)===d);return `<button class="body-eval-card eval-button" data-eval-date="${esc(d)}"><div class="body-card-head"><div><span class="body-kicker">Avaliação</span><h3>${prettyDate(d)}</h3></div><span class="pill">${[weight,measures,bio,skin].filter(Boolean).length} grupos</span></div><div class="eval-summary">${weight?`<div><span>Peso</span><strong>${fmt(weightVal(weight))} kg</strong></div>`:''}${measures?`<div><span>Cintura</span><strong>${fmt(measures.cintura||measures.cintura_cm)} cm</strong></div>`:''}${skin?`<div><span>Adipometria</span><strong>${fmt(skin.bodyFatPct)}%</strong></div>`:''}${bio?`<div><span>Bioimpedância</span><strong>${fmt(bio.bodyFatPct||bio.fatMassPct)}%</strong></div>`:''}</div><div class="eval-tags">${weight?'<span>Peso</span>':''}${measures?'<span>Medidas</span>':''}${bio?'<span>Bioimpedância</span>':''}${skin?'<span>Adipometria</span>':''}</div></button>`}).join('')}</div>`}
function bodyEvaluationModal(date){const w=objRows(FILES.body,'Peso').find(x=>x.date===date),m=objRows(FILES.body,'Medidas').find(x=>x.date===date),b=objRows(FILES.body,'Bioimpedancia').find(x=>x.date===date),s=objRows(FILES.body,'Adipometria').find(x=>x.date===date);state.modal=`<div class="modalhead"><div><h3>Avaliação — ${prettyDate(date)}</h3><div class="muted">Todos os registros encontrados nesta data.</div></div><button class="x" data-close>×</button></div>${w?`<div class="detail-section"><h4>Peso</h4><strong>${fmt(weightVal(w))} kg</strong><span class="muted"> • ${esc(w.source||'Manual')}</span></div>`:''}${m?`<div class="detail-section"><h4>Medidas</h4><div class="measure-grid">${measureChip('Cintura',m.cintura)}${measureChip('Abdômen',m.abdomen)}${measureChip('Quadril',m.quadril)}${measureChip('Tórax',m.torax)}</div></div>`:''}${s?`<div class="detail-section"><h4>Adipometria</h4><div class="bio-grid">${bioMetric('Soma',s.sumFoldsMm,' mm')}${bioMetric('% gordura',s.bodyFatPct,'%')}${bioMetric('Massa de gordura',s.fatMassKg,' kg')}${bioMetric('Massa livre',s.leanMassKg,' kg')}</div></div>`:''}${b?`<div class="detail-section"><h4>Bioimpedância — ${esc(b.source||'')}</h4><div class="bio-grid">${bioMetric('% gordura',b.bodyFatPct||b.fatMassPct,'%')}${bioMetric('Massa de gordura',b.fatMassKg,' kg')}${bioMetric('Massa livre',b.fatFreeMassKg,' kg')}${bioMetric('Gordura visceral',b.visceralFat,'')}</div></div>`:''}`;render()}

function bodyEvolutionSeries(metric){if(metric==='weight')return bodyWeightRowsSorted().map(x=>({date:x.date,value:weightVal(x)}));if(['waist','abdomen'].includes(metric)){const key=metric==='waist'?'cintura':'abdomen';return objRows(FILES.body,'Medidas').map(x=>({date:x.date,value:num(x[key])}))}if(metric==='fatPctAdipo')return objRows(FILES.body,'Adipometria').map(x=>({date:x.date,value:num(x.bodyFatPct)}));if(metric==='fatMass')return objRows(FILES.body,'Adipometria').map(x=>({date:x.date,value:num(x.fatMassKg)}));if(metric==='leanMass')return objRows(FILES.body,'Adipometria').map(x=>({date:x.date,value:num(x.leanMassKg)}));if(metric==='folds')return objRows(FILES.body,'Adipometria').map(x=>({date:x.date,value:num(x.sumFoldsMm)}));return []}
bodyEvo=function(){const labels={weight:['Peso',' kg'],waist:['Cintura',' cm'],abdomen:['Abdômen',' cm'],fatPctAdipo:['% gordura — adipometria','%'],fatMass:['Massa de gordura',' kg'],leanMass:['Massa livre de gordura',' kg'],folds:['Soma das dobras',' mm']},l=labels[state.bodyEvoMetric],series=bodyEvolutionSeries(state.bodyEvoMetric).filter(x=>inPeriod(x.date,state.bodyEvoPeriod)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return `<div class="train-toolbar"><div><h3>Evolução corporal</h3><span class="muted">Uma métrica por vez, sem misturar métodos.</span></div><div><select id="bodyEvoMetric">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${state.bodyEvoMetric===k?'selected':''}>${v[0]}</option>`).join('')}</select><select id="bodyEvoPeriod"><option value="30" ${state.bodyEvoPeriod==='30'?'selected':''}>30 dias</option><option value="90" ${state.bodyEvoPeriod==='90'?'selected':''}>3 meses</option><option value="180" ${state.bodyEvoPeriod==='180'?'selected':''}>6 meses</option><option value="365" ${state.bodyEvoPeriod==='365'?'selected':''}>1 ano</option><option value="all" ${state.bodyEvoPeriod==='all'?'selected':''}>Tudo</option></select></div></div><div class="grid">${card('Registros',series.length)}${card('Primeiro',series.length?fmt(series[0].value)+l[1]:'—')}${card('Último',series.length?fmt(series.at(-1).value)+l[1]:'—')}${card('Variação',series.length>1?`${series.at(-1).value-series[0].value>0?'+':''}${fmt(series.at(-1).value-series[0].value)}${l[1]}`:'—')}</div><div class="card chart-card">${simpleLineChart(series,l[1])}</div>`}

/* BINDINGS NOVOS */
const _bindBaseV3=bind;
bind=function(){
  _bindBaseV3();
  document.querySelectorAll('[data-food-favorite]').forEach(b=>b.onclick=()=>toggleFoodFavorite(b.dataset.foodFavorite));
  document.getElementById('copyNutDay')?.addEventListener('click',copyNutDayModal);
  document.getElementById('clearNutDay')?.addEventListener('click',clearNutDay);
  document.getElementById('confirmCopyNutDay')?.addEventListener('click',copyNutDay);
  document.getElementById('nutEvoMetric')?.addEventListener('change',e=>{state.nutEvoMetric=e.target.value;render()});
  document.getElementById('nutEvoPeriod')?.addEventListener('change',e=>{state.nutEvoPeriod=e.target.value;render()});
  document.getElementById('bodyWeightPeriod')?.addEventListener('change',e=>{state.bodyWeightPeriod=e.target.value;render()});
  document.getElementById('bodyEvoMetric')?.addEventListener('change',e=>{state.bodyEvoMetric=e.target.value;render()});
  document.getElementById('bodyEvoPeriod')?.addEventListener('change',e=>{state.bodyEvoPeriod=e.target.value;render()});
  document.getElementById('bodyOverviewDate')?.addEventListener('change',e=>{state.bodyOverviewDate=e.target.value;render()});
  document.querySelectorAll('[data-eval-date]').forEach(b=>b.onclick=()=>bodyEvaluationModal(b.dataset.evalDate));
  document.getElementById('duplicateTrainWeek')?.addEventListener('click',duplicateTrainingWeek);
  document.getElementById('exportTrainCsv')?.addEventListener('click',downloadTrainingCsv);
  document.querySelectorAll('[data-save-template]').forEach(b=>b.onclick=()=>saveTrainingAsTemplate(b.dataset.saveTemplate));
  document.querySelectorAll('[data-use-template]').forEach(b=>b.onclick=()=>useTrainingTemplate(b.dataset.useTemplate));
}


/* AF+ v3.1 — estabilidade, backup/restauração e proteção das planilhas */
FILES.config='AF_PLUS_CONFIG.xlsx';
if(!MODS.some(m=>m[0]==='settings')) MODS.push(['settings','⚙','Configurações']);
Object.assign(state,{lastAutoBackupAt:0,saveBusy:false});

function validateSheetPayload(file,sheet,data){
  if(!file||!String(file).toLowerCase().endsWith('.xlsx'))throw new Error('Arquivo XLSX inválido.');
  if(!sheet||!String(sheet).trim())throw new Error('Aba inválida.');
  if(!Array.isArray(data)||!data.length||!Array.isArray(data[0]))throw new Error('A planilha precisa manter uma linha de cabeçalho.');
  if(data.length>100000)throw new Error('Quantidade de linhas acima do limite de segurança.');
  const headers=data[0].map(v=>String(v??'').trim());
  if(headers.some(h=>!h))throw new Error('Há uma coluna sem nome no cabeçalho.');
  const lowered=headers.map(h=>h.toLowerCase());
  if(new Set(lowered).size!==lowered.length)throw new Error('Há colunas duplicadas no cabeçalho.');
  for(let r=1;r<data.length;r++){
    if(!Array.isArray(data[r]))throw new Error(`Linha ${r+1} inválida.`);
    if(data[r].length>headers.length)throw new Error(`Linha ${r+1} possui mais colunas que o cabeçalho.`);
  }
  return true;
}
function friendlySaveError(err){
  const msg=String(err?.message||err||'Erro desconhecido');
  if(/permission|denied|used by another|being used|process cannot access|bloque|423|409/i.test(msg))return 'Não foi possível salvar. Feche esta planilha no Excel e tente novamente.';
  return `Não foi possível salvar na planilha: ${msg}`;
}
async function ensureAutoBackup(){
  const now=Date.now();
  if(now-num(state.lastAutoBackupAt)<5*60*1000)return;
  try{const r=await fetch('/api/backup');if(r.ok)state.lastAutoBackupAt=now}catch(e){/* backup manual continua disponível */}
}
const _saveSheetV30=saveSheet;
saveSheet=async function(file,sheet,data){
  validateSheetPayload(file,sheet,data);
  if(state.saveBusy)throw new Error('Já existe uma gravação em andamento. Aguarde alguns segundos.');
  state.saveBusy=true;
  try{
    const r=await fetch('/api/save-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file,sheet,rows:data})});
    if(!r.ok)throw new Error(await r.text());
    state.books[file]??={};state.books[file][sheet]=data;
    toast('Salvo no Google Sheets');
    // Backup fora do caminho crítico: não bloqueia a gravação nem a interface.
    setTimeout(()=>ensureAutoBackup(),250);
  }catch(e){
    const msg=friendlySaveError(e);toast(msg);throw new Error(msg);
  }finally{state.saveBusy=false}
};

window.saveSheetsBatch=async function(items){
  const list=(Array.isArray(items)?items:[]).filter(Boolean);
  if(!list.length)return;
  list.forEach(it=>validateSheetPayload(it.file,it.sheet,it.rows));
  if(state.saveBusy)throw new Error('Já existe uma gravação em andamento. Aguarde alguns segundos.');
  state.saveBusy=true;
  try{
    const r=await fetch('/api/save-batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:list})});
    const txt=await r.text();
    if(!r.ok)throw new Error(txt);
    list.forEach(it=>{state.books[it.file]??={};state.books[it.file][it.sheet]=it.rows;});
    toast('Salvo no Google Sheets');
    try{localStorage.setItem('afplus:books-cache',JSON.stringify({at:Date.now(),books:state.books}));}catch(_){ }
    setTimeout(()=>ensureAutoBackup(),250);
    return JSON.parse(txt||'{}');
  }catch(e){
    const msg=friendlySaveError(e);toast(msg);throw new Error(msg);
  }finally{state.saveBusy=false}
};

function dataHealth(){
  const required=[FILES.nutrition,FILES.training,FILES.body,FILES.agenda,FILES.reading,FILES.media,FILES.trips,FILES.integrations,FILES.config];
  let filesOk=0,sheets=0,invalid=0;
  required.forEach(f=>{const book=state.books[f];if(book){filesOk++;Object.entries(book).forEach(([name,data])=>{if(name==='CONFIG')return;sheets++;try{validateSheetPayload(f,name,data)}catch(e){invalid++}})}});
  return {required:required.length,filesOk,sheets,invalid};
}
function settingsPage(){
  const h=dataHealth(),cfg=objRows(FILES.config,'CONFIG'),ver=cfg.find(x=>String(x.chave)==='versao')?.valor||'3.1';
  return shell(hero('CONFIGURAÇÕES','Proteção dos arquivos locais, backup e manutenção do AF+.')+`
    <div class="grid">
      ${card('Versão',esc(ver),'AF+ Local XLSX')}
      ${card('Planilhas',`${h.filesOk}/${h.required}`,'arquivos carregados')}
      ${card('Abas verificadas',h.sheets,'estrutura lida')}
      ${card('Problemas estruturais',h.invalid,h.invalid?'revisar antes de continuar':'nenhum detectado')}
    </div>
    <div class="settings-grid">
      <section class="settings-card"><h3>Backup</h3><p>O AF+ cria uma cópia de segurança antes das gravações, com intervalo de proteção para evitar dezenas de backups iguais.</p><div class="actions"><button class="btn primary" id="settingsBackup">Criar backup agora</button><button class="btn" id="settingsOpenData">Abrir pasta DADOS</button></div></section>
      <section class="settings-card"><h3>Restauração</h3><p>Para restaurar com segurança, feche o AF+ e o Excel e execute <strong>RESTAURAR_BACKUP.bat</strong>. O estado atual é salvo antes da restauração.</p><span class="status-pill good">Proteção pré-restauração incluída</span></section>
      <section class="settings-card"><h3>Exportar / importar tudo</h3><p><strong>EXPORTAR_DADOS.bat</strong> cria um ZIP da pasta DADOS. <strong>IMPORTAR_DADOS.bat</strong> recebe um ZIP e preserva uma cópia dos dados atuais.</p><span class="status-pill">Sem alterar a interface do AF+</span></section>
      <section class="settings-card"><h3>Planilha aberta no Excel</h3><p>Se o Windows bloquear um XLSX aberto, o AF+ interrompe a gravação e mostra um aviso para você fechar a planilha antes de tentar novamente.</p><span class="status-pill good">Validação antes de salvar</span></section>
      <section class="settings-card"><h3>Atualização de versão</h3><p>A pasta <strong>DADOS</strong> é independente da interface. Ao atualizar o AF+, mantenha a pasta DADOS e faça um backup antes da troca de versão.</p><span class="status-pill">Dados preservados</span></section>
      <section class="settings-card"><h3>Auditoria</h3><p>Execute <strong>AUDITAR_DADOS.bat</strong> quando quiser validar se todos os XLSX abrem como arquivos válidos e se as planilhas principais estão presentes.</p><div class="actions"><button class="btn" id="settingsReload">Recarregar dados</button></div></section>
    </div>`,'Configurações')
}
const _renderV30=render;
render=function(){
  if(state.page==='settings'){app.innerHTML=settingsPage();bind();return}
  _renderV30();
};
const _bindV31Base=bind;
bind=function(){
  _bindV31Base();
  document.getElementById('settingsBackup')?.addEventListener('click',async()=>{try{const r=await fetch('/api/backup');if(!r.ok)throw new Error(await r.text());const j=await r.json();state.lastAutoBackupAt=Date.now();toast(`Backup criado: ${j.files||0} planilhas`)}catch(e){toast('Não foi possível criar o backup.')}});
  document.getElementById('settingsOpenData')?.addEventListener('click',()=>fetch('/api/open-data'));
  document.getElementById('settingsReload')?.addEventListener('click',load);
};

load().catch(e=>{app.innerHTML=`<div class="boot"><div class="brandbig">AF<span>+</span></div><h2>Não foi possível carregar os dados do Google Sheets.</h2><p>O AF+ está em modo Netlify + Google Sheets. Verifique a conexão com a API e tente atualizar a página.</p><pre>${esc(e.message)}</pre></div>`});

