/* AF+ v8.0 — camada final de produto
   Não altera schemas dos XLSX. Acrescenta análises derivadas, MM7, busca,
   central de dados/pendências, atalhos, diagnóstico e acabamento de uso diário. */
(() => {
  const AF_VERSION='11.2.1';
  const AF_BUILD='20260927';
  const AF_EXPECTED_XLSX=9;
  const ui={dirty:false,lastSave:localStorage.getItem('afplus:lastSave')||'',period:localStorage.getItem('afplus:period')||'30'};
  Object.assign(state,{systemTab:'health',globalQuery:'',analyticsPeriod:ui.period});

  const isoDate=v=>{const s=String(v??'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);return''};
  const dayMs=86400000;
  const toDate=s=>{const d=isoDate(s);return d?new Date(`${d}T12:00:00`):null};
  const diffDays=(a,b)=>{const da=toDate(a),db=toDate(b);return da&&db?Math.round((da-db)/dayMs):null};
  const sum=(a,fn=x=>num(x))=>a.reduce((s,x)=>s+num(fn(x)),0);
  const avg=a=>a.length?sum(a)/a.length:0;
  const finite=v=>Number.isFinite(Number(v))?Number(v):0;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const statusTone=s=>/erro|crít|crit|problema/i.test(s)?'bad':/pend|aten|revis|incomplet/i.test(s)?'warn':'good';
  const fmt2=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(finite(n));
  const monthKey=()=>today().slice(0,7);
  const daysBack=(n,end=today())=>{const d=toDate(end)||new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
  const within=(d,start,end)=>{d=isoDate(d);return !!d&&d>=start&&d<=end};
  const uniqueDays=rows=>new Set(rows.map(x=>isoDate(x.date||x.data_referencia||x.data)).filter(Boolean)).size;
  const prettyMaybeDate=v=>isoDate(v)?brDate(isoDate(v)):String(v??'');

  function groupDaily(rows,dateField,valueFn){const m=new Map();rows.forEach(r=>{const d=isoDate(r[dateField]??r.date);if(!d)return;m.set(d,(m.get(d)||0)+finite(valueFn(r)))});return [...m].map(([date,value])=>({date,value})).sort((a,b)=>a.date.localeCompare(b.date))}
  function dailyLast(rows,dateField,valueFn){const m=new Map();rows.forEach(r=>{const d=isoDate(r[dateField]??r.date);if(!d)return;m.set(d,finite(valueFn(r)))});return [...m].map(([date,value])=>({date,value})).sort((a,b)=>a.date.localeCompare(b.date))}
  function calendarWindow(series,endDate,days=7){if(!series.length)return[];const end=endDate||series.at(-1).date,start=daysBack(days-1,end);return series.filter(x=>within(x.date,start,end))}
  function movingCalendar(series,days=7){return series.map((p,i)=>{const start=daysBack(days-1,p.date),window=series.filter((x,j)=>j<=i&&within(x.date,start,p.date));return {...p,ma:window.length?avg(window.map(x=>x.value)):null,count:window.length}})}
  function windowCompare(series,days=7){if(!series.length)return{current:0,previous:0,delta:0,count:0};const end=series.at(-1).date,curStart=daysBack(days-1,end),prevEnd=daysBack(days,end),prevStart=daysBack(days*2-1,end);const cur=series.filter(x=>within(x.date,curStart,end)),prev=series.filter(x=>within(x.date,prevStart,prevEnd));const current=cur.length?avg(cur.map(x=>x.value)):0,previous=prev.length?avg(prev.map(x=>x.value)):0;return{current,previous,delta:current-previous,count:cur.length,previousCount:prev.length,end}}
  function trendWord(delta,tolerance=.05){return Math.abs(delta)<=tolerance?'estável':delta<0?'queda':'alta'}
  function trendChip(delta,unit=''){const cls=delta<0?'down':delta>0?'up':'flat';return `<span class="af-trend ${cls}">${delta>0?'+':''}${fmt2(delta)}${unit?` ${unit}`:''}</span>`}

  function weightSeries(){return dailyLast(objRows(FILES.body,'Peso'),'date',x=>x.weightKg||x.weight||x.peso)}
  function nutritionSeries(field='kcal'){return groupDaily(consumptionRows(),'date',x=>x[field]??x[{protein:'proteinG',carbs:'carbsG',fat:'fatG',fiber:'fiberG'}[field]])}
  function waterSeries(){return groupDaily(waterRows(),'date',x=>x.ml)}
  function trainingSeries(field='duration'){return groupDaily(trainingRows(),'date',x=>field==='distance'?x.executedDistanceKm||x.plannedDistanceKm:field==='calories'?x.calories:x.executedDurationMin||x.plannedDurationMin)}
  function readingSeries(){return groupDaily(objRows(FILES.reading,'Sessoes'),'date',x=>x.durationMin||0)}
  function pendingSummary(){const pendingOptions=objRows(FILES.nutrition,'Resumo_Opcoes').filter(x=>String(x.status||'').toUpperCase()!=='OK').length;let auditIssues=0;try{auditIssues=modelAudit().issues||0}catch(e){}const imports=objRows(FILES.training,'Importacao_Atividades').filter(x=>!['aprovado','concluído','concluido','ignorado'].includes(String(x.reviewStatus||'').toLowerCase())).length;return{pendingOptions,tasks:0,overdue:0,auditIssues,imports,total:pendingOptions+auditIssues+imports}}

  function svgLine(series,{height=150,ma=true,goal=null}={}){
    const data=series.slice(-90);if(data.length<2)return `<div class="af-chart-empty">Dados insuficientes para o gráfico.</div>`;
    const mov=ma?movingCalendar(data,7):data.map(x=>({...x,ma:null}));const vals=[...data.map(x=>x.value),...mov.map(x=>x.ma).filter(v=>v!=null),...(goal!=null?[goal]:[])];let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const w=760,p=20,sy=v=>height-p-((v-min)/(max-min))*(height-2*p),sx=i=>p+i*(w-2*p)/(data.length-1);const points=data.map((x,i)=>`${sx(i)},${sy(x.value)}`).join(' '),mapoints=mov.map((x,i)=>x.ma==null?null:`${sx(i)},${sy(x.ma)}`).filter(Boolean).join(' ');const goalLine=goal==null?'':`<line x1="${p}" x2="${w-p}" y1="${sy(goal)}" y2="${sy(goal)}" class="af-goal-line"/>`;
    return `<div class="af-chart-wrap"><svg viewBox="0 0 ${w} ${height}" role="img" aria-label="Evolução"><line x1="${p}" x2="${w-p}" y1="${height-p}" y2="${height-p}" class="af-axis"/>${goalLine}<polyline points="${points}" class="af-line-raw"/>${ma?`<polyline points="${mapoints}" class="af-line-ma"/>`:''}</svg><div class="af-chart-legend"><span><i class="raw"></i>Registro</span>${ma?'<span><i class="ma"></i>MM7</span>':''}${goal!=null?'<span><i class="goal"></i>Meta</span>':''}</div></div>`
  }

  function dataHealth(){
    const pairs=Object.entries(FILES),files=pairs.length+1;let sheets=0,records=0,empty=0;const modules=[];pairs.forEach(([key,file])=>{const book=state.books[file]||{};const names=Object.keys(book);sheets+=names.length;let rc=0;names.forEach(s=>rc+=Math.max(0,(book[s]?.length||1)-1));records+=rc;if(rc===0)empty++;modules.push({key,file,sheets:names.length,records:rc,ok:names.length>0})});let audit={issues:0,missingFoodNutrition:0};try{audit=modelAudit()}catch(e){}return{files,sheets,records,empty,modules,audit,expected:AF_EXPECTED_XLSX}}

  function overviewV8(){
    const ws=weightSeries(),wc=windowCompare(ws,7),last=ws.at(-1),ns=nutritionSeries('kcal'),nw=windowCompare(ns,7),water=waterSeries(),ww=windowCompare(water,7),ts=trainingSeries('duration'),tw=windowCompare(ts,7),p=pendingSummary(),todayNut=todayNutritionTotals(),todayWaterVal=todayWater(),todayTrain=trainingForDate(today());
    return shell(
      hero('AF+','Seu dia e suas tendências em uma única visão. Os indicadores são derivados dos XLSX existentes; nenhum valor ausente é inventado.')+
      `<div class="af-kpi-grid">
        ${metricCard('Peso atual',last?`${fmt2(last.value)} kg`:'—',last?brDate(last.date):'sem registro',wc.count?`MM7 ${fmt2(wc.current)} kg • ${trendWord(wc.delta)}`:'MM7 parcial',wc.delta,'kg')}
        ${metricCard('Nutrição hoje',`${fmt2(todayNut.kcal)} kcal`,`${fmt2(todayNut.protein)} g proteína`,nw.count?`MM7 ${fmt2(nw.current)} kcal`:'sem histórico suficiente')}
        ${metricCard('Água hoje',`${fmt2(todayWaterVal)} ml`,ww.count?`MM7 ${fmt2(ww.current)} ml`:'MM7 sem dados',waterGoalText())}
        ${metricCard('Treinos hoje',todayTrain.length,`${fmt2(sum(todayTrain,x=>x.executedDurationMin||x.plannedDurationMin))} min`,tw.count?`MM7 ${fmt2(tw.current)} min/dia`:'sem histórico suficiente')}
        ${metricCard('Pendências',p.total,p.total?'itens que merecem revisão':'nenhuma pendência crítica',`${p.pendingOptions} nutrição • ${p.imports} importações`)}
        ${metricCard('Dados','XLSX','9 arquivos separados','auditoria e backup preservados')}
      </div>`+
      `<div class="af-dashboard-two"><section class="card af-chart-card"><div class="sectiontitle"><div><span class="body-kicker">Corpo</span><h3>Peso e média móvel de 7 dias</h3></div><button class="btn small" data-v8-go="body|weight">Abrir Corpo</button></div>${svgLine(ws,{height:170,ma:true})}${wc.count?`<div class="af-insight"><strong>MM7:</strong> ${fmt2(wc.current)} kg ${trendChip(wc.delta,'kg')} <span class="muted">vs. janela anterior</span></div>`:''}</section>
      <section class="card"><div class="sectiontitle"><div><span class="body-kicker">Hoje</span><h3>Ações rápidas</h3></div></div><div class="af-quick-actions"><button class="btn" data-v8-action="weight">+ Peso</button><button class="btn" data-v8-go="nutrition|today">Nutrição</button><button class="btn" data-v8-go="training|week">Treinos</button><button class="btn" data-v8-action="event">+ Evento</button><button class="btn" data-v8-go="reading|today">Leitura</button></div>${todayAgendaAndTasks()}</section></div>`+
      `<div class="af-dashboard-two"><section class="card"><div class="sectiontitle"><div><span class="body-kicker">Tendências</span><h3>Últimos 7 dias</h3></div></div>${trendRows([{label:'Peso MM7',value:wc.current,suffix:' kg',delta:wc.delta},{label:'Calorias MM7',value:nw.current,suffix:' kcal',delta:nw.delta},{label:'Água MM7',value:ww.current,suffix:' ml',delta:ww.delta},{label:'Treino MM7',value:tw.current,suffix:' min',delta:tw.delta}])}</section><section class="card"><div class="sectiontitle"><div><span class="body-kicker">Pendências</span><h3>Central de atenção</h3></div><button class="btn small" id="openSystemCenter">Ver central</button></div>${pendingRows(p)}</section></div>`,
      'Visão geral'
    );
  }
  function metricCard(t,v,s='',detail='',delta=null,unit=''){return `<article class="card af-metric-card"><div class="af-card-top"><h3>${esc(t)}</h3>${delta!=null?trendChip(delta,unit):''}</div><div class="metric">${esc(v)}</div><div class="muted">${esc(s)}</div>${detail?`<small>${esc(detail)}</small>`:''}</article>`}
  function waterGoalText(){const g=goalsRows().at(-1),goal=finite(g?.waterMl);return goal?`meta ${fmt2(goal)} ml`:'meta não definida'}
  function trendRows(items){return `<div class="af-trend-list">${items.map(x=>`<div><span>${esc(x.label)}</span><strong>${x.value?`${fmt2(x.value)}${x.suffix}`:'—'}</strong>${x.value?trendChip(x.delta,x.suffix.trim()):''}</div>`).join('')}</div>`}
  function pendingRows(p){const rows=[['Nutrição',p.pendingOptions,'opções PENDENTE'],['Treinos',p.imports,'importações para revisar'],['Integridade',p.auditIssues,'inconsistências relacionais']];return `<div class="af-pending-list">${rows.map(([l,n,s])=>`<div class="${n?'has':'ok'}"><span>${esc(l)}</span><strong>${n}</strong><small>${esc(s)}</small></div>`).join('')}</div>`}
  function todayAgendaAndTasks(){const ag=objRows(FILES.agenda,'Agenda').filter(x=>isoDate(x.date)===today()&&!['cancelado'].includes(String(x.status||'').toLowerCase())&&!['sim','true','1'].includes(String(x.archived||'').toLowerCase())).sort((a,b)=>String(a.start||'').localeCompare(String(b.start||'')));return `<div class="af-today-list"><h4>Agenda de hoje</h4>${ag.slice(0,6).map(x=>`<div><strong>${esc(x.start||'Dia inteiro')}</strong><span>${esc(x.title||'Compromisso')}</span></div>`).join('')||'<span class="muted">Nenhum compromisso para hoje.</span>'}</div>`}

  function bodyWeightV8(){const ws=weightSeries();if(!ws.length)return `<div class="module-actions"><button class="btn primary" id="addBodyWeight">+ Adicionar peso</button></div><div class="card empty">Nenhum peso registrado.</div>`;const last=ws.at(-1),prev=ws.at(-2),wc=windowCompare(ws,7),m= movingCalendar(ws,7);return `<div class="module-actions"><button class="btn primary" id="addBodyWeight">+ Adicionar peso</button><div class="af-period-pills"><button class="btn small ${state.bodyWeightPeriod==='30'?'primary':''}" data-v8-weight-period="30">30D</button><button class="btn small ${state.bodyWeightPeriod==='90'?'primary':''}" data-v8-weight-period="90">90D</button><button class="btn small ${state.bodyWeightPeriod==='all'?'primary':''}" data-v8-weight-period="all">Tudo</button></div></div><div class="af-kpi-grid af-body-kpis">${metricCard('Último peso',`${fmt2(last.value)} kg`,brDate(last.date),prev?`${last.value-prev.value>0?'+':''}${fmt2(last.value-prev.value)} kg vs anterior`:'primeiro registro')}${metricCard('Média móvel 7 dias',wc.count?`${fmt2(wc.current)} kg`:'—',wc.count<7?`média parcial • ${wc.count} dia(s) com registro`:'janela completa',wc.previousCount?`${wc.delta>0?'+':''}${fmt2(wc.delta)} kg vs janela anterior`:'sem janela anterior',wc.previousCount?wc.delta:null,'kg')}${metricCard('Registros',ws.length,`${uniqueDays(ws)} dia(s)`,`${brDate(ws[0].date)} → ${brDate(last.date)}`)}${metricCard('Amplitude',`${fmt2(Math.max(...ws.map(x=>x.value))-Math.min(...ws.map(x=>x.value)))} kg`,`mín. ${fmt2(Math.min(...ws.map(x=>x.value)))} • máx. ${fmt2(Math.max(...ws.map(x=>x.value)))}`,'histórico completo')}</div><section class="card af-chart-card"><div class="sectiontitle"><div><span class="body-kicker">Tendência</span><h3>Peso diário + MM7</h3></div></div>${svgLine(filterWeightPeriod(ws),{height:210,ma:true})}<div class="af-insight">A MM7 usa os registros disponíveis dentro dos 7 dias de calendário anteriores a cada ponto. Quando há menos de 7 dias registrados, o AF+ mostra a média como parcial.</div></section><div class="sectiontitle"><h3>Histórico</h3><span class="muted">${ws.length} registro(s)</span></div><div class="body-timeline">${ws.slice().reverse().map((x,i)=>{const older=ws[ws.length-2-i],d=older?x.value-older.value:null,mi=m.find(z=>z.date===x.date);return `<article class="body-record"><div class="body-record-date">${brDate(x.date)}</div><div class="body-record-main"><div><strong>${fmt2(x.value)} kg</strong><small class="af-mm-inline">MM7 ${mi?.ma!=null?fmt2(mi.ma)+' kg':'—'}${mi?.count<7?` • parcial ${mi?.count||0}/7`:''}</small></div>${d!=null?`<span class="body-mini ${d<=0?'good':''}">${d>0?'+':''}${fmt2(d)} kg vs anterior</span>`:'<span class="body-mini">Primeiro registro</span>'}</div>${bodyRecordActions(x)}</article>`}).join('')}</div>`}
  function bodyRecordActions(x){return `<div class="record-actions"><button class="btn" data-edit-weight="${esc(x.id)}">Editar</button><button class="btn danger" data-delete-body="Peso|${esc(x.id)}">Excluir</button></div>`}
  function filterWeightPeriod(ws){const p=state.bodyWeightPeriod||'90';if(p==='all')return ws;const start=daysBack(Number(p)-1,ws.at(-1)?.date||today());return ws.filter(x=>x.date>=start)}

  function globalSearchIndex(){const entries=[];const fileToPage=Object.fromEntries(Object.entries(FILES).map(([p,f])=>[f,p]));Object.entries(state.books).forEach(([file,book])=>{const page=fileToPage[file]||'overview';Object.entries(book||{}).forEach(([sheet,matrix])=>{if(page==='agenda'&&['Tarefas','Rotinas'].includes(sheet))return;if(!matrix?.length)return;const h=matrix[0].map(String);matrix.slice(1).forEach((row,ri)=>{if(!row?.some(v=>v!==''&&v!=null))return;const o=Object.fromEntries(h.map((k,i)=>[k,row[i]]));const label=o.title||o.name||o.nome||o.description||o.opcao_nome||o.workoutName||o.date||o.data||o.id||`Registro ${ri+1}`;const text=Object.values(o).filter(v=>v!=null&&typeof v!=='object').join(' • ');entries.push({page,file,sheet,label:String(label),text,id:o.id||''})})})});return entries}
  function openGlobalSearch(q=''){state.globalQuery=q;const idx=globalSearchIndex(),n=q.trim().toLowerCase(),res=n?idx.filter(x=>`${x.label} ${x.text} ${x.sheet}`.toLowerCase().includes(n)).slice(0,60):idx.slice(0,20);state.modal=`<div class="modalhead"><div><h3>Busca global</h3><div class="muted">Pesquise nos dados já carregados dos módulos.</div></div><button class="x" data-close>×</button></div><div class="af-searchbox"><input id="globalSearchInput" value="${esc(q)}" placeholder="Buscar alimento, evento, livro, treino, viagem..." autofocus><span>${res.length} resultado(s)</span></div><div class="af-search-results">${res.map(x=>`<button data-v8-search-result="${esc(x.page)}|${esc(x.sheet)}|${esc(x.id)}"><strong>${esc(x.label)}</strong><span>${esc(moduleLabel(x.page))} • ${esc(x.sheet)}</span><small>${esc(x.text.slice(0,180))}</small></button>`).join('')||'<div class="card empty">Nenhum resultado.</div>'}</div>`;render();setTimeout(()=>{const el=document.getElementById('globalSearchInput');el?.focus();if(el){el.setSelectionRange(el.value.length,el.value.length);el.addEventListener('input',e=>openGlobalSearch(e.target.value))}},0)}
  function moduleLabel(page){return MODS.find(x=>x[0]===page)?.[2]||page}

  function systemCenter(){const h=dataHealth(),p=pendingSummary();return shell(hero('CENTRAL DO AF+','Saúde dos dados, pendências, diagnóstico e manutenção. Esta tela não altera os dados automaticamente.')+`<div class="tabs"><button class="tab ${state.systemTab==='health'?'active':''}" data-v8-sys="health">Integridade</button><button class="tab ${state.systemTab==='pending'?'active':''}" data-v8-sys="pending">Pendências</button><button class="tab ${state.systemTab==='maintenance'?'active':''}" data-v8-sys="maintenance">Manutenção</button><button class="tab ${state.systemTab==='about'?'active':''}" data-v8-sys="about">Sobre</button></div>${state.systemTab==='health'?healthTab(h):state.systemTab==='pending'?pendingTab(p):state.systemTab==='maintenance'?maintenanceTab():aboutTab(h)}`,'Central do AF+')}
  function healthTab(h){return `<div class="af-kpi-grid">${metricCard('Arquivos XLSX',h.files,`esperados: ${h.expected}`,h.files===h.expected?'estrutura reconhecida':'revisar quantidade')}${metricCard('Abas carregadas',h.sheets,'em todos os módulos','leitura em memória')}${metricCard('Registros',h.records,'linhas de dados carregadas','sem contar cabeçalhos')}${metricCard('Integridade',h.audit.issues?'REVISAR':'OK',h.audit.issues?`${h.audit.issues} inconsistência(s)`:'relações válidas',`${h.audit.missingFoodNutrition||0} alimento(s) sem macros`)}</div><div class="sectiontitle"><h3>Arquivos reconhecidos</h3><span class="muted">fonte: pasta DADOS</span></div><div class="af-health-grid">${h.modules.map(m=>`<article class="card"><div class="af-card-top"><strong>${esc(m.file)}</strong><span class="af-status ${m.ok?'good':'bad'}">${m.ok?'OK':'ERRO'}</span></div><div class="af-health-meta"><span>${m.sheets} abas</span><span>${m.records} registros</span></div></article>`).join('')}<article class="card"><div class="af-card-top"><strong>AF_PLUS_CONFIG.xlsx</strong><span class="af-status good">OK</span></div><div class="af-health-meta"><span>configuração global</span><span>v${AF_VERSION}</span></div></article></div>`}
  function pendingTab(p){const pendOpts=objRows(FILES.nutrition,'Resumo_Opcoes').filter(x=>String(x.status||'').toUpperCase()!=='OK'),imports=objRows(FILES.training,'Importacao_Atividades').filter(x=>!['aprovado','concluído','concluido','ignorado'].includes(String(x.reviewStatus||'').toLowerCase()));return `<div class="af-kpi-grid">${metricCard('Total',p.total,'itens para revisão')}${metricCard('Nutrição',p.pendingOptions,'opções PENDENTE')}${metricCard('Importações',p.imports,'aguardando revisão')}</div>${pendingSection('Nutrição — PENDENTE',pendOpts.map(x=>[x.opcao_nome||x.opcao_base,x.pendencias||'dados insuficientes']),'nutrition|options')}${pendingSection('Importações para revisar',imports.map(x=>[x.fileName||x.modality,`${x.date||''} • ${x.reviewStatus||'Pendente'}`]),'training|imports')}`}
  function pendingSection(title,items,go){return `<section class="card af-pending-section"><div class="sectiontitle"><h3>${esc(title)}</h3><button class="btn small" data-v8-go="${esc(go)}">Abrir</button></div>${items.length?items.slice(0,20).map(([a,b])=>`<div class="af-pending-row"><strong>${esc(a||'Registro')}</strong><span>${esc(b||'')}</span></div>`).join(''):'<div class="muted">Nenhuma pendência.</div>'}</section>`}
  function maintenanceTab(){return `<div class="af-maint-grid"><button class="card af-maint-btn" id="v8Backup"><strong>Backup agora</strong><span>Cria cópia dos XLSX usando a rotina existente.</span></button><button class="card af-maint-btn" id="v8Reload"><strong>Recarregar dados</strong><span>Lê novamente os arquivos locais.</span></button><button class="card af-maint-btn" id="v8OpenData"><strong>Abrir pasta DADOS</strong><span>Acessa os XLSX oficiais.</span></button><button class="card af-maint-btn" id="v8Search"><strong>Busca global</strong><span>Localiza registros em todos os módulos carregados.</span></button></div><div class="card af-maint-note"><strong>Proteção ativa</strong><p>O AF+ continua usando as rotinas existentes de backup pré-gravação, validação estrutural e XLSX separados. Operações destrutivas não são executadas automaticamente por esta central.</p></div>`}
  function aboutTab(h){return `<div class="card af-about"><div class="brandbig">AF<span>+</span></div><h3>AF+ ${AF_VERSION}</h3><p>Build ${AF_BUILD} • Finalização sobre a base v7.0 auditada.</p><div class="af-about-grid"><span><strong>${h.expected}</strong>XLSX esperados</span><span><strong>${h.sheets}</strong>abas carregadas</span><span><strong>${h.records}</strong>registros</span><span><strong>Local</strong>armazenamento</span></div><p class="muted">A camada final adiciona análises derivadas (incluindo MM7), central de dados, busca global, atalhos, indicadores e acabamento sem inventar dados ausentes nem recalcular opções nutricionais PENDENTE.</p></div>`}

  function enhancedShell(content,title='AF+'){
    return `<div class="layout af-v8-layout"><aside class="sidebar"><div class="brand">AF<span>+</span><small>v11</small></div><div class="navlabel">Painel</div>${MODS.map(m=>`<button class="navbtn ${state.page===m[0]?'active':''}" data-page="${m[0]}"><span class="ico">${m[1]}</span><span>${m[2]}</span></button>`).join('')}<div class="navlabel">Sistema</div><button class="navbtn ${state.page==='system'?'active':''}" id="systemCenter"><span class="ico">⚙</span><span>Central do AF+</span></button><button class="navbtn" id="openData"><span class="ico">▣</span><span>Abrir DADOS</span></button><div class="sidefoot">AF+ ${AF_VERSION}<br>build ${AF_BUILD}<br>localhost • XLSX locais</div></aside><section class="main"><header class="top"><div class="af-top-title"><h1>${esc(title)}</h1><span class="af-save-state">${ui.lastSave?`Último salvamento ${esc(ui.lastSave)}`:'Dados locais'}</span></div><div class="actions af-top-actions"><button class="btn af-search-trigger" id="globalSearch">⌕ <span>Buscar</span><kbd>Ctrl K</kbd></button><button class="btn" id="backup">Backup XLSX</button><button class="btn" id="reload">Atualizar</button></div></header><div class="content">${content}</div></section></div>${state.modal?`<div class="modalback" id="modalback"><div class="modal">${state.modal}</div></div>`:''}`
  }

  const originalShell=shell,originalOverview=overview,originalBodyWeight=bodyWeightView,originalRender=render,originalBind=bind,originalSaveSheet=saveSheet;
  shell=enhancedShell;
  overview=overviewV8;
  bodyWeightView=bodyWeightV8;
  saveSheet=async function(file,sheet,data){try{await originalSaveSheet(file,sheet,data);ui.lastSave=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});localStorage.setItem('afplus:lastSave',ui.lastSave);ui.dirty=false}catch(e){const raw=String(e?.message||e||'Erro desconhecido');const locked=/permissionerror|permission denied|access is denied|sharing violation|used by another process|winerror\s*32|errno\s*13/i.test(raw);const clean=raw.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,240);if(locked)toast(`Não foi possível salvar ${file} / ${sheet}: o arquivo está bloqueado por outro programa.`);else toast(`Falha ao salvar ${sheet}: ${clean||'erro não identificado'}`);console.error('AF+ save error',{file,sheet,error:e});throw e}};
  render=function(){if(state.page==='system'){app.innerHTML=systemCenter();bind();return}originalRender()};

  function goSpec(spec){const [page,sub]=String(spec||'').split('|');state.page=page;if(page==='body'&&sub)state.bodyTab=sub;if(page==='nutrition'&&sub)state.nutTab=sub;if(page==='training'&&sub)state.trainTab=sub;if(page==='reading'&&sub)state.readTab=sub;if(GENERIC_CFG?.[page]&&sub){state.genericTabs=state.genericTabs||{};state.genericTabs[page]=sub}state.modal=null;render()}
  function bindV8(){
    document.getElementById('systemCenter')?.addEventListener('click',()=>{state.page='system';state.systemTab='health';render()});
    document.getElementById('openSystemCenter')?.addEventListener('click',()=>{state.page='system';state.systemTab='pending';render()});
    document.getElementById('globalSearch')?.addEventListener('click',()=>openGlobalSearch());
    document.querySelectorAll('[data-v8-go]').forEach(b=>b.addEventListener('click',()=>goSpec(b.dataset.v8Go)));
    document.querySelectorAll('[data-v8-sys]').forEach(b=>b.addEventListener('click',()=>{state.systemTab=b.dataset.v8Sys;render()}));
    document.querySelectorAll('[data-v8-weight-period]').forEach(b=>b.addEventListener('click',()=>{state.bodyWeightPeriod=b.dataset.v8WeightPeriod;render()}));
    document.querySelectorAll('[data-v8-search-result]').forEach(b=>b.addEventListener('click',()=>{const [page]=b.dataset.v8SearchResult.split('|');state.modal=null;state.page=page;render()}));
    document.querySelectorAll('[data-v8-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.v8Action;if(a==='weight')bodyWeightModal();if(a==='event'){if(window.afAgendaNew)window.afAgendaNew();else{state.page='agenda';render()}}}));
    document.getElementById('v8Backup')?.addEventListener('click',()=>document.getElementById('backup')?.click());
    document.getElementById('v8Reload')?.addEventListener('click',()=>load());
    document.getElementById('v8OpenData')?.addEventListener('click',()=>fetch('/api/open-data'));
    document.getElementById('v8Search')?.addEventListener('click',()=>openGlobalSearch());
    document.querySelectorAll('.modal input,.modal select,.modal textarea').forEach(el=>el.addEventListener('input',()=>ui.dirty=true));document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',()=>ui.dirty=false));
  }
  bind=function(){originalBind();bindV8()};

  window.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openGlobalSearch()}
    if(e.key==='Escape'&&state.modal){state.modal=null;ui.dirty=false;render()}
  });
  window.addEventListener('beforeunload',e=>{if(ui.dirty){e.preventDefault();e.returnValue=''}});

  // Insere marca de versão sem alterar os dados do usuário.
  try{localStorage.setItem('afplus:version',AF_VERSION);localStorage.setItem('afplus:build',AF_BUILD)}catch(e){}
})();

/* AF+ v8.0 — acabamento transversal dos módulos genéricos */
(() => {
  state.genericSearch=state.genericSearch||{};
  state.genericPeriod=state.genericPeriod||{};
  state.v8Undo=null;
  const _genericRowsTable=genericRowsTable,_generic=generic,_bind=bind,_deleteGeneric=deleteGeneric;
  const dateFields=['date','day','dueDate','nextCharge','startedAt','finishedAt','answeredAt','createdAt','updatedAt'];
  const getDate=o=>{for(const f of dateFields){const v=String(o[f]??'');if(/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10)}return''};
  const periodStart=(p,end=today())=>{if(p==='all')return'0000-01-01';const n=Number(p||30),d=new Date(`${end}T12:00:00`);d.setDate(d.getDate()-(n-1));return d.toISOString().slice(0,10)};
  function filteredGeneric(page,sheet){const actual=genericActualSheet(page,sheet);let objs=objRows(FILES[page],actual);if(page==='media'&&sheet==='Filmes')objs=objs.filter(x=>String(x.type||'').toLowerCase()==='filme');if(page==='media'&&sheet==='Series')objs=objs.filter(x=>['série','serie'].includes(String(x.type||'').toLowerCase()));if(page==='media'&&sheet==='Novelas')objs=objs.filter(x=>String(x.type||'').toLowerCase()==='novela');const q=String(state.genericSearch[page]||'').trim().toLowerCase();if(q)objs=objs.filter(o=>Object.values(o).some(v=>String(v??'').toLowerCase().includes(q)));const p=state.genericPeriod[page]||'all';if(p!=='all'){const start=periodStart(p);objs=objs.filter(o=>{const d=getDate(o);return !d||d>=start})}return objs}
  genericRowsTable=function(page,sheet){if(page==='agenda'&&sheet==='Agenda')return agendaCalendar();if(page==='agenda'&&sheet==='Semana')return agendaWeek();const actual=genericActualSheet(page,sheet),objs=filteredGeneric(page,sheet),raw=rows(FILES[page],actual),headers=(raw[0]||[]).map(String).filter(h=>!HIDDEN_GENERIC_FIELDS.has(h));if(!headers.length)return '<div class="card empty">Estrutura não encontrada.</div>';const preferred=['date','title','name','description','type','category','status','amount','progress','durationMin','priority'];const visible=[...preferred.filter(h=>headers.includes(h)),...headers.filter(h=>!preferred.includes(h))].slice(0,8);return `<div class="smart-table-wrap"><table class="table smart-table"><thead><tr>${visible.map(h=>`<th>${esc(friendlyField(h))}</th>`).join('')}<th>Ações</th></tr></thead><tbody>${objs.map(o=>`<tr>${visible.map(h=>`<td>${genericCell(h,o[h])}</td>`).join('')}<td><div class="row-actions"><button class="btn small" data-generic-edit="${esc(o.id||'')}" data-sheet="${esc(actual)}">Editar</button><button class="btn small danger" data-generic-delete="${esc(o.id||'')}" data-sheet="${esc(actual)}">Excluir</button></div></td></tr>`).join('')||`<tr><td colspan="${visible.length+1}" class="muted">Nenhum registro para os filtros atuais.</td></tr>`}</tbody></table></div>`}
  function genericCell(h,v){if(v==null||v==='')return '<span class="muted">—</span>';if(/^\d{4}-\d{2}-\d{2}/.test(String(v)))return esc(brDate(String(v).slice(0,10)));if(/status/i.test(h)){const s=String(v),tone=/concl|feito|pago|ativo|confirm/i.test(s)?'good':/atras|erro|cancel/i.test(s)?'bad':'warn';return `<span class="af-status ${tone}">${esc(s)}</span>`}if(/amount|balance|invoice|budget|invested|remaining/i.test(h))return `R$ ${fmt(v)}`;return esc(v)}
  generic=function(page){const cfg=GENERIC_CFG[page],f=FILES[page];if(!cfg)return _generic(page);const active=genericActiveSheet(page),actual=genericActualSheet(page,active),label=cfg.tabs.find(x=>x[0]===active)?.[1]||active,filtered=filteredGeneric(page,active),allCount=objRows(f,actual).length;return shell(hero(MODS.find(x=>x[0]===page)?.[2]||page,cfg.subtitle)+`<div class="grid smart-kpis">${genericSummary(page)}</div><div class="module-toolbar"><div class="tabs">${cfg.tabs.map(([id,l])=>`<button class="tab ${active===id?'active':''}" data-gtab="${id}">${l}</button>`).join('')}</div><button class="btn primary" id="genericNew">+ Novo registro</button></div>${!['Agenda','Semana'].includes(active)?`<div class="af-module-filters"><input id="v8GenericSearch" value="${esc(state.genericSearch[page]||'')}" placeholder="Buscar neste módulo..."><div class="af-period-pills"><button class="btn small ${(state.genericPeriod[page]||'all')==='all'?'primary':''}" data-v8-gperiod="all">Tudo</button><button class="btn small ${state.genericPeriod[page]==='30'?'primary':''}" data-v8-gperiod="30">30D</button><button class="btn small ${state.genericPeriod[page]==='90'?'primary':''}" data-v8-gperiod="90">90D</button></div></div>`:''}<div class="sectiontitle"><div><span class="body-kicker">${esc(label)}</span><h3>${filtered.length} de ${allCount} registro(s)</h3></div></div>${genericRowsTable(page,active)}`,MODS.find(x=>x[0]===page)?.[2]||'AF+')}

  deleteGeneric=async function(page,sheet,id){if(!confirm('Excluir este registro? Você poderá desfazer a última exclusão nesta sessão.'))return;const f=FILES[page],raw=rows(f,sheet),headers=(raw[0]||[]).map(String),objs=objRows(f,sheet),removed=objs.find(x=>String(x.id||'')===String(id));if(!removed)return;state.v8Undo={page,sheet,file:f,row:{...removed},headers:[...headers]};await saveSheet(f,sheet,toRows(objs.filter(x=>String(x.id||'')!==String(id)),headers));toast('Registro excluído. Use Desfazer no topo se necessário.');render()}
  async function undoLast(){const u=state.v8Undo;if(!u)return;const objs=objRows(u.file,u.sheet);if(!objs.some(x=>String(x.id||'')===String(u.row.id||'')))objs.push(u.row);await saveSheet(u.file,u.sheet,toRows(objs,u.headers));state.v8Undo=null;toast('Exclusão desfeita');render()}

  bind=function(){_bind();document.getElementById('v8GenericSearch')?.addEventListener('input',e=>{state.genericSearch[state.page]=e.target.value;render();setTimeout(()=>{const x=document.getElementById('v8GenericSearch');if(x){x.focus();x.setSelectionRange(x.value.length,x.value.length)}},0)});document.querySelectorAll('[data-v8-gperiod]').forEach(b=>b.addEventListener('click',()=>{state.genericPeriod[state.page]=b.dataset.v8Gperiod;render()}));if(state.v8Undo){const a=document.querySelector('.top .actions');if(a&&!document.getElementById('v8Undo')){const b=document.createElement('button');b.id='v8Undo';b.className='btn';b.textContent='↶ Desfazer exclusão';b.onclick=undoLast;a.prepend(b)}}};
})();
