/* AF+ v4.0 — fechamento funcional dos módulos principais */
Object.assign(state,{bodyCompareA:'',bodyCompareB:''});

function modelAudit(){
  const foods=foodRows(),plans=planRows(),planItems=planItemRows(),cons=consumptionRows(),consItems=consumptionItemRows();
  const foodIds=new Set(foods.map(foodId).filter(Boolean).map(String));
  const planIds=new Set(plans.map(x=>String(x.id||'')).filter(Boolean));
  const conIds=new Set(cons.map(x=>String(x.id||'')).filter(Boolean));
  const trainIds=new Set(trainingRows().map(x=>String(x.id||'')).filter(Boolean));
  const missingFoodNutrition=foods.filter(f=>num(f.kcal)===0&&num(f.proteinG)===0&&num(f.carbsG)===0&&num(f.fatG)===0).length;
  const orphanPlanItems=planItems.filter(x=>!planIds.has(String(x.planId||''))).length;
  const orphanConsumptionItems=consItems.filter(x=>!conIds.has(String(x.consumptionId||''))).length;
  const orphanBlocks=trainingBlockRows().filter(x=>!trainIds.has(String(x.trainingId||''))).length;
  const missingFoodRefs=[...planItems,...consItems].filter(x=>x.foodId&&!foodIds.has(String(x.foodId))).length;
  const byName={};foods.forEach(f=>{const k=foodName(f).trim().toLowerCase();if(k)(byName[k]??=[]).push(f)});
  const duplicateFoodNames=Object.values(byName).filter(v=>v.length>1).length;
  const duplicateWeights=(()=>{const m={};objRows(FILES.body,'Peso').forEach(x=>{const k=`${x.date}|${x.source||''}`;(m[k]??=[]).push(x)});return Object.values(m).filter(v=>v.length>1).length})();
  const issues=orphanPlanItems+orphanConsumptionItems+orphanBlocks+missingFoodRefs+duplicateFoodNames+duplicateWeights;
  return {missingFoodNutrition,orphanPlanItems,orphanConsumptionItems,orphanBlocks,missingFoodRefs,duplicateFoodNames,duplicateWeights,issues};
}
function finalAuditHtml(){const a=modelAudit();return `<div class="final-audit"><div class="${a.issues?'warn':''}"><span>Relações de dados</span><strong>${a.issues?'Revisar':'OK'}</strong><small>${a.issues} inconsistência(s)</small></div><div class="${a.missingFoodNutrition?'warn':''}"><span>Base nutricional</span><strong>${a.missingFoodNutrition?'Incompleta':'OK'}</strong><small>${a.missingFoodNutrition} alimento(s) sem macros</small></div><div class="${a.orphanBlocks?'warn':''}"><span>Treinos / blocos</span><strong>${a.orphanBlocks?'Revisar':'OK'}</strong><small>${a.orphanBlocks} bloco(s) órfão(s)</small></div><div class="${a.duplicateWeights?'warn':''}"><span>Corpo</span><strong>${a.duplicateWeights?'Revisar':'OK'}</strong><small>${a.duplicateWeights} duplicidade(s)</small></div></div>`}

/* Visão geral integrada */
const _overviewV40=overview;
overview=function(){
  const n=todayNutritionTotals(),water=todayWater(),tr=trainingForDate(today()),w=bodyWeightRowsSorted(),last=w.at(-1),a=modelAudit();
  const core=hero('AF+','Seu sistema pessoal usando arquivos XLSX locais como fonte dos dados.')+`<div class="grid">${card('Nutrição hoje',fmt(n.kcal)+' kcal',`${fmt(n.protein)} g proteína • ${fmt(water)} ml água`)}${card('Treinos hoje',tr.length,tr.length?'planejado/executado':'nenhum treino')}${card('Último peso',last?fmt(weightVal(last))+' kg':'—',last?brDate(last.date):'sem registro')}${card('Integridade',a.issues?'Revisar':'OK',a.issues?`${a.issues} inconsistência(s)`:'relações válidas')}</div><div class="sectiontitle"><h3>Saúde dos dados</h3><span class="muted">Validação automática</span></div>${finalAuditHtml()}`;
  return shell(core,'Visão geral');
};

/* Nutrição */
function nutWeekTotals(){return DAYS.map((day,i)=>{const t=plannedTotalsForDay(i),meals=mealNames().filter(m=>pickPlan(i,m)).length;return {day,i,...t,meals}})}
function nutWeekSummaryFinal(){const data=nutWeekTotals(),total=data.reduce((a,x)=>{a.kcal+=x.kcal;a.protein+=x.protein;a.fiber+=x.fiber;a.meals+=x.meals;return a},{kcal:0,protein:0,fiber:0,meals:0});return `<div class="sectiontitle"><h3>Resumo do planejamento semanal</h3><span class="muted">Soma do que está planejado</span></div><div class="grid">${card('Refeições',total.meals)}${card('Calorias',fmt(total.kcal)+' kcal')}${card('Proteína',fmt(total.protein)+' g')}${card('Fibra',fmt(total.fiber)+' g')}</div><div class="week-mini-summary">${data.map(x=>`<button type="button" class="week-mini-day ${x.i===state.day?'active':''}" data-nut-select-day="${x.i}"><strong>${x.day}</strong><span>${x.meals} refeições</span><small>${fmt(x.kcal)} kcal</small></button>`).join('')}</div>`}
const _nutWeekV40=nutWeek;
nutWeek=function(){return `${nutWeekSummaryFinal()}<div class="module-actions"><button class="btn" id="copyNutMeal">Copiar uma refeição</button><button class="btn" id="copyNutDay">Copiar dia selecionado</button><button class="btn" id="clearNutDay">Limpar planejamento do dia</button><span class="muted">Dia selecionado: ${DAYS[state.day]}</span></div>${_nutWeekV40().replace(/<div class="module-actions">[\s\S]*?<\/div>/,'')}`};
function copyNutMealModal(){state.modal=`<div class="modalhead"><div><h3>Copiar uma refeição</h3><div class="muted">Duplica o planejamento e os alimentos montados.</div></div><button class="x" data-close>×</button></div><div class="formgrid"><div class="field"><label>Refeição de origem</label><select id="copyMealSource">${mealNames().map(m=>`<option>${esc(m)}</option>`).join('')}</select></div><div class="field"><label>Dia de destino</label><select id="copyMealDay">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></div><div class="field"><label>Refeição de destino</label><select id="copyMealTarget">${mealNames().map(m=>`<option>${esc(m)}</option>`).join('')}</select></div></div><div class="actions" style="margin-top:14px"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="confirmCopyNutMeal">Copiar refeição</button></div>`;render()}
async function copyNutMeal(){const srcMeal=document.getElementById('copyMealSource')?.value||'',targetDay=Number(document.getElementById('copyMealDay')?.value),targetMeal=document.getElementById('copyMealTarget')?.value||srcMeal,src=pickPlan(state.day,srcMeal);if(!src){toast('A refeição de origem não tem planejamento.');return}const headers=rows(FILES.nutrition,'Planejamento')[0].map(String),plans=planRows(),itemHeaders=rows(FILES.nutrition,'Planejamento_Itens')[0].map(String),items=planItemRows(),now=new Date().toISOString();plans.filter(p=>String(p.day).toUpperCase()===DAYS[targetDay]&&String(p.meal||'').toLowerCase()===targetMeal.toLowerCase()).forEach(p=>p.status='cancelado');const nid='plan-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);plans.push({...src,id:nid,day:DAYS[targetDay],date:'',meal:targetMeal,copiedFromId:src.id,status:'planejado',source:'copia-refeicao',createdAt:now,updatedAt:now});items.filter(it=>String(it.planId)===String(src.id)).forEach((it,i)=>items.push({...it,id:`${nid}-item-${i+1}`,planId:nid,createdAt:now}));await saveSheet(FILES.nutrition,'Planejamento',toRows(plans,headers));await saveSheet(FILES.nutrition,'Planejamento_Itens',toRows(items,itemHeaders));state.modal=null;state.day=targetDay;render()}
function nutritionAuditModal(){const a=nutritionAudit(),foods=foodRows(),missing=foods.filter(f=>num(f.kcal)===0&&num(f.proteinG)===0&&num(f.carbsG)===0&&num(f.fatG)===0),byName={};foods.forEach(f=>{const k=foodName(f).trim().toLowerCase();if(k)(byName[k]??=[]).push(f)});const dups=Object.entries(byName).filter(([,v])=>v.length>1);const optIssues=optionRows().filter(o=>String(o.calc_status||'OK')!=='OK');state.modal=`<div class="modalhead"><div><h3>Auditoria da Nutrição</h3><div class="muted">Alimentos e opções de refeição são verificados sem inventar valores ausentes.</div></div><button class="x" data-close>×</button></div>${finalAuditHtml()}<div class="detail-section"><h4>Opções com pendências (${optIssues.length})</h4><div class="audit-list">${optIssues.slice(0,40).map(o=>`<span><strong>${esc(optionName(o))}</strong> • ${esc(o.descricao||'')} — ${esc(o.calc_status||'')} ${o.calc_note?'• '+esc(o.calc_note):''}</span>`).join('')||'<span>Nenhuma.</span>'}</div></div><div class="detail-section"><h4>Sem dados nutricionais (${a.missing})</h4><div class="audit-list">${missing.slice(0,30).map(f=>`<span>${esc(foodName(f))}</span>`).join('')||'<span>Nenhum.</span>'}</div></div><div class="detail-section"><h4>Possíveis duplicados (${a.duplicates})</h4><div class="audit-list">${dups.slice(0,20).map(([,v])=>`<span>${esc(v[0].name)} • ${v.length} registros</span>`).join('')||'<span>Nenhum.</span>'}</div></div>`;render()}
const _foodsTabV40=foodsTab;foodsTab=function(){return `<div class="module-actions"><button class="btn" id="openNutritionAudit">Auditar base alimentar</button><span class="muted">Complete os valores do rótulo/porção para cálculos confiáveis.</span></div>${_foodsTabV40()}`};

/* Treinos */
trainWeekSummary=function(dates){const list=trainingRows().filter(x=>dates.includes(String(x.date||''))),done=list.filter(x=>trainStatus(x)==='executado'),planned=list.filter(x=>trainStatus(x)!=='executado'),mods={};list.forEach(x=>{const m=trainModality(x)||'Outro';mods[m]??={planned:0,done:0,min:0,dist:0};if(trainStatus(x)==='executado'){mods[m].done++;mods[m].min+=num(x.executedDurationMin);mods[m].dist+=num(x.executedDistanceKm)}else mods[m].planned++});const plannedMin=list.reduce((s,x)=>s+num(x.plannedDurationMin),0),execMin=done.reduce((s,x)=>s+num(x.executedDurationMin),0),execDist=done.reduce((s,x)=>s+num(x.executedDistanceKm),0),cal=done.reduce((s,x)=>s+num(x.calories),0);return `<div class="grid">${card('Planejados',planned.length,`${durationText(plannedMin)} previstos`)}${card('Executados',done.length,`${durationText(execMin)} realizados`)}${card('Distância',fmt(execDist)+' km','executada')}${card('Calorias',fmt(cal)+' kcal','registradas')}</div><div class="modality-summary">${Object.entries(mods).map(([m,v])=>`<div><strong>${esc(m)}</strong><span>${v.done} executado(s) • ${v.planned} pendente(s)</span><small>${durationText(v.min)}${v.dist?` • ${fmt(v.dist)} km`:''}</small></div>`).join('')||'<div>Sem treinos nesta semana.</div>'}</div>`};

/* Corpo */
function bodyDates(){return [...new Set([...objRows(FILES.body,'Peso'),...objRows(FILES.body,'Medidas'),...objRows(FILES.body,'Bioimpedancia'),...objRows(FILES.body,'Adipometria')].map(x=>x.date).filter(Boolean))].sort()}
function bodyRecordByDate(sheet,date){return objRows(FILES.body,sheet).filter(x=>String(x.date)===String(date)).at(-1)||null}
function deltaText(a,b,unit=''){if(a===null||b===null||!Number.isFinite(a)||!Number.isFinite(b))return '—';const d=b-a;return `${d>0?'+':''}${fmt(d)}${unit}`}
function bodyComparePanel(){const dates=bodyDates();if(!dates.length)return '';const a=state.bodyCompareA||dates.at(-2)||dates.at(-1),b=state.bodyCompareB||dates.at(-1);state.bodyCompareA=a;state.bodyCompareB=b;const wa=bodyRecordByDate('Peso',a),wb=bodyRecordByDate('Peso',b),ma=bodyRecordByDate('Medidas',a),mb=bodyRecordByDate('Medidas',b),aa=bodyRecordByDate('Adipometria',a),ab=bodyRecordByDate('Adipometria',b);const metrics=[['Peso',wa?weightVal(wa):null,wb?weightVal(wb):null,' kg'],['Cintura',ma?num(ma.cintura):null,mb?num(mb.cintura):null,' cm'],['Abdômen',ma?num(ma.abdomen):null,mb?num(mb.abdomen):null,' cm'],['% gordura (adipo)',aa?num(aa.bodyFatPct):null,ab?num(ab.bodyFatPct):null,'%'],['Soma das dobras',aa?num(aa.sumFoldsMm):null,ab?num(ab.sumFoldsMm):null,' mm']];return `<div class="compare-toolbar"><div><h3>Comparar avaliações</h3><span class="muted">Peso, medidas e adipometria sem misturar métodos de bioimpedância.</span></div><div><select id="bodyCompareA">${dates.map(d=>`<option value="${d}" ${d===a?'selected':''}>${brDate(d)}</option>`).join('')}</select><span>→</span><select id="bodyCompareB">${dates.map(d=>`<option value="${d}" ${d===b?'selected':''}>${brDate(d)}</option>`).join('')}</select></div></div><div class="measure-compare">${metrics.map(([l,av,bv,u])=>`<div><span>${l}</span><strong>${bv!==null&&Number.isFinite(bv)?fmt(bv)+u:'—'}</strong><small>${deltaText(av,bv,u)}</small></div>`).join('')}</div>`}
const _bodyEvaluationsV40=bodyEvaluations;bodyEvaluations=function(){return `${bodyComparePanel()}${_bodyEvaluationsV40()}`};

/* Configurações */
const _settingsPageV40=settingsPage;settingsPage=function(){const a=modelAudit(),base=_settingsPageV40(),checks=[['Backup automático',true],['Restauração protegida',true],['Validação XLSX',true],['Nutrição: plano + consumos reais',true],['Treinos: planejado × executado',true],['Corpo: métodos separados',true],['Relações internas',a.issues===0],['Base alimentar completa',a.missingFoodNutrition===0]],panel=`<div class="sectiontitle"><h3>Checklist da versão final</h3><span class="muted">Estrutura funcional + qualidade dos dados</span></div>${finalAuditHtml()}<div class="final-checklist">${checks.map(([l,ok])=>`<div class="${ok?'ok':'warn'}"><span>${ok?'✓':'!'}</span><strong>${l}</strong><small>${ok?'OK':'Revisar dados'}</small></div>`).join('')}</div>`;return base.replace('<div class="settings-grid">',panel+'<div class="settings-grid">')};

const _bindV40Base=bind;bind=function(){_bindV40Base();document.querySelectorAll('[data-nut-select-day]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.nutSelectDay);render()});document.getElementById('copyNutMeal')?.addEventListener('click',copyNutMealModal);document.getElementById('confirmCopyNutMeal')?.addEventListener('click',copyNutMeal);document.getElementById('openNutritionAudit')?.addEventListener('click',nutritionAuditModal);document.getElementById('bodyCompareA')?.addEventListener('change',e=>{state.bodyCompareA=e.target.value;render()});document.getElementById('bodyCompareB')?.addEventListener('change',e=>{state.bodyCompareB=e.target.value;render()})};

/* AF+ v4.2 — Corpo: inclusão, edição e exclusão de registros */
function bodyActionBar(label,id){return `<div class="module-actions body-add-actions"><button class="btn primary" id="${id}">+ ${label}</button></div>`}
function bodyRowById(sheet,id){return objRows(FILES.body,sheet).find(x=>String(x.id||'')===String(id||''))||null}
function bodyFormField(id,label,value='',type='number',step='0.1',extra=''){return `<label class="field"><span>${label}</span><input id="${id}" type="${type}" ${type==='number'?`step="${step}"`:''} value="${esc(value??'')}" ${extra}></label>`}
function bodySelectField(id,label,value,opts){return `<label class="field"><span>${label}</span><select id="${id}">${opts.map(o=>{const v=Array.isArray(o)?o[0]:o,l=Array.isArray(o)?o[1]:o;return `<option value="${esc(v)}" ${String(v)===String(value||'')?'selected':''}>${esc(l)}</option>`}).join('')}</select></label>`}
function bodyVal(id){return document.getElementById(id)?.value?.trim()||''}
function bodyNumOrBlank(id){const v=bodyVal(id);return v===''?'':Number(v.replace(',','.'))}
function bodyNow(){return new Date().toISOString()}
async function bodySaveObject(sheet,obj,editId=''){
  const hdr=rows(FILES.body,sheet)[0].map(String),all=objRows(FILES.body,sheet);let idx=editId?all.findIndex(x=>String(x.id)===String(editId)):-1;
  if(idx>=0)all[idx]={...all[idx],...obj,updatedAt:bodyNow()};else all.push(obj);
  await saveSheet(FILES.body,sheet,toRows(all,hdr));state.modal=null;render();
}
async function bodyDeleteRecord(sheet,id){if(!confirm('Excluir este registro? Esta ação altera a planilha local.'))return;const hdr=rows(FILES.body,sheet)[0].map(String),all=objRows(FILES.body,sheet).filter(x=>String(x.id)!==String(id));await saveSheet(FILES.body,sheet,toRows(all,hdr));render()}

function bodyWeightModal(id=''){const x=bodyRowById('Peso',id)||{},date=x.date||today();state.modal=`<div class="modalhead"><div><h3>${id?'Editar':'Adicionar'} peso</h3><div class="muted">Registro salvo em AF_PLUS_CORPO.xlsx.</div></div><button class="x" data-close>×</button></div><div class="formgrid">${bodyFormField('bwDate','Data',date,'date','','required')}${bodyFormField('bwKg','Peso (kg)',x.weightKg||'','number','0.1','required')}${bodySelectField('bwSource','Origem',x.source||'Manual',['Manual','Nutricionista','Relaxmedic/Fitdays'])}<label class="field wide"><span>Observação</span><textarea id="bwNotes" rows="3">${esc(x.notes||'')}</textarea></label></div><div class="actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveBodyWeight">Salvar peso</button></div>`;render();setTimeout(()=>{document.getElementById('saveBodyWeight')?.addEventListener('click',async()=>{const kg=bodyNumOrBlank('bwKg');if(!bodyVal('bwDate')||kg===''){toast('Informe data e peso');return}await bodySaveObject('Peso',{id:id||`peso-${Date.now()}`,userId:x.userId||'default',date:bodyVal('bwDate'),weightKg:kg,createdAt:x.createdAt||bodyNow(),source:bodyVal('bwSource'),notes:bodyVal('bwNotes')},id)})},0)}

function bodyMeasuresModal(id=''){const x=bodyRowById('Medidas',id)||{};const fields=[['bmPescoco','Pescoço','pescoco'],['bmTorax','Tórax','torax'],['bmOmbro','Ombro','ombro'],['bmCintura','Cintura','cintura'],['bmQuadril','Quadril','quadril'],['bmAbdomen','Abdômen','abdomen'],['bmBraER','Braço E relaxado','bracoEsqRelaxado'],['bmBraDR','Braço D relaxado','bracoDirRelaxado'],['bmBraEC','Braço E contraído','bracoEsqContraido'],['bmBraDC','Braço D contraído','bracoDirContraido'],['bmAnteE','Antebraço E','antebracoEsq'],['bmAnteD','Antebraço D','antebracoDir'],['bmCoxaE','Coxa E','coxaEsq'],['bmCoxaD','Coxa D','coxaDir'],['bmPantE','Panturrilha E','panturrilhaEsq'],['bmPantD','Panturrilha D','panturrilhaDir']];state.modal=`<div class="modalhead"><div><h3>${id?'Editar':'Adicionar'} medidas</h3><div class="muted">Medidas corporais em centímetros.</div></div><button class="x" data-close>×</button></div><div class="formgrid">${bodyFormField('bmDate','Data',x.date||today(),'date','','required')}${bodySelectField('bmSource','Origem',x.source||'Nutricionista',['Manual','Nutricionista','Relaxmedic/Fitdays'])}</div><h4 class="modal-section-title">Tronco</h4><div class="formgrid">${fields.slice(0,6).map(f=>bodyFormField(f[0],f[1]+' (cm)',x[f[2]]||'')).join('')}</div><h4 class="modal-section-title">Membros superiores</h4><div class="formgrid">${fields.slice(6,12).map(f=>bodyFormField(f[0],f[1]+' (cm)',x[f[2]]||'')).join('')}</div><h4 class="modal-section-title">Membros inferiores</h4><div class="formgrid">${fields.slice(12).map(f=>bodyFormField(f[0],f[1]+' (cm)',x[f[2]]||'')).join('')}<label class="field wide"><span>Observação</span><textarea id="bmNotes" rows="3">${esc(x.notes||'')}</textarea></label></div><div class="actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveBodyMeasures">Salvar medidas</button></div>`;render();setTimeout(()=>document.getElementById('saveBodyMeasures')?.addEventListener('click',async()=>{if(!bodyVal('bmDate')){toast('Informe a data');return}const o={id:id||`med-${Date.now()}`,userId:x.userId||'default',date:bodyVal('bmDate'),createdAt:x.createdAt||bodyNow(),source:bodyVal('bmSource'),notes:bodyVal('bmNotes')};fields.forEach(f=>o[f[2]]=bodyNumOrBlank(f[0]));o.peito=o.torax;o.braco=o.bracoDirRelaxado;o.coxa=o.coxaDir;o.panturrilha=o.panturrilhaDir;await bodySaveObject('Medidas',o,id)}),0)}

function bodyBioModal(id=''){const x=bodyRowById('Bioimpedancia',id)||{};state.modal=`<div class="modalhead"><div><h3>${id?'Editar':'Adicionar'} bioimpedância</h3><div class="muted">Mantenha Casa/Relaxmedic separado da avaliação profissional.</div></div><button class="x" data-close>×</button></div><div class="formgrid">${bodyFormField('bbDate','Data',x.date||today(),'date','','required')}${bodySelectField('bbSource','Origem',x.source||'Casa',[['Casa','Casa — Relaxmedic/Fitdays'],['Nutricionista','Nutricionista — profissional'],['Manual','Manual']])}${bodyFormField('bbEquipment','Equipamento',x.equipment||'','text')}${bodyFormField('bbApp','Aplicativo/Fonte',x.appSource||'','text')}${bodyFormField('bbWeight','Peso (kg)',x.weightKg||'')}${bodyFormField('bbFatPct','Gordura corporal (%)',x.bodyFatPct||x.fatMassPct||'')}${bodyFormField('bbFatKg','Massa de gordura (kg)',x.fatMassKg||'')}${bodyFormField('bbLeanKg','Massa livre de gordura (kg)',x.fatFreeMassKg||'')}${bodyFormField('bbMuscleKg','Massa muscular (kg)',x.muscleMassKg||'')}${bodyFormField('bbWaterPct','Água corporal (%)',x.bodyWaterPct||'')}${bodyFormField('bbVisceral','Gordura visceral',x.visceralFat||'')}${bodyFormField('bbBmi','IMC',x.bmi||'')}${bodyFormField('bbBmr','Metabolismo basal (kcal)',x.bmrKcal||'','number','1')}${bodyFormField('bbAge','Idade corporal',x.bodyAge||'','number','1')}<label class="field wide"><span>Observação</span><textarea id="bbNotes" rows="3">${esc(x.observations||'')}</textarea></label></div><div class="actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveBodyBio">Salvar bioimpedância</button></div>`;render();setTimeout(()=>document.getElementById('saveBodyBio')?.addEventListener('click',async()=>{if(!bodyVal('bbDate')){toast('Informe a data');return}const o={...x,id:id||`bio-${Date.now()}`,userId:x.userId||'default',date:bodyVal('bbDate'),source:bodyVal('bbSource'),equipment:bodyVal('bbEquipment'),appSource:bodyVal('bbApp'),observations:bodyVal('bbNotes'),createdAt:x.createdAt||bodyNow(),weightKg:bodyNumOrBlank('bbWeight'),fatMassKg:bodyNumOrBlank('bbFatKg'),bodyFatPct:bodyNumOrBlank('bbFatPct'),fatMassPct:bodyNumOrBlank('bbFatPct'),fatFreeMassKg:bodyNumOrBlank('bbLeanKg'),muscleMassKg:bodyNumOrBlank('bbMuscleKg'),bodyWaterPct:bodyNumOrBlank('bbWaterPct'),visceralFat:bodyNumOrBlank('bbVisceral'),bmi:bodyNumOrBlank('bbBmi'),bmrKcal:bodyNumOrBlank('bbBmr'),bodyAge:bodyNumOrBlank('bbAge')};await bodySaveObject('Bioimpedancia',o,id)}),0)}

function bodySkinModal(id=''){const x=bodyRowById('Adipometria',id)||{},folds=parseFolds(x.measurements),fv=n=>folds.find(f=>String(f.label||'').toLowerCase().includes(n))?.mm||'';state.modal=`<div class="modalhead"><div><h3>${id?'Editar':'Adicionar'} adipometria</h3><div class="muted">Protocolo de 3 dobras: Tricipital + Abdominal + Suprailíaca.</div></div><button class="x" data-close>×</button></div><div class="formgrid">${bodyFormField('bsDate','Data',x.date||today(),'date','','required')}${bodySelectField('bsSource','Origem',x.source||'Nutricionista',['Nutricionista','Manual'])}${bodyFormField('bsWeight','Peso na avaliação (kg)',x.weightKg||'')}${bodyFormField('bsTri','Tricipital (mm)',fv('tricip'))}${bodyFormField('bsAbd','Abdominal (mm)',fv('abdominal'))}${bodyFormField('bsSup','Suprailíaca (mm)',fv('suprail'))}${bodyFormField('bsDensity','Densidade corporal',x.bodyDensity||'','number','0.001')}${bodyFormField('bsFatPct','Gordura corporal (%)',x.bodyFatPct||'')}${bodyFormField('bsFatKg','Massa de gordura (kg)',x.fatMassKg||'')}${bodyFormField('bsLeanKg','Massa livre de gordura (kg)',x.leanMassKg||'')}${bodyFormField('bsClass','Classificação',x.bodyFatClass||'','text')}<label class="field wide"><span>Observação</span><textarea id="bsNotes" rows="3">${esc(x.observations||'')}</textarea></label></div><div class="modal-total" id="skinSumPreview">Soma das dobras: —</div><div class="actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveBodySkin">Salvar adipometria</button></div>`;render();setTimeout(()=>{const upd=()=>{const s=['bsTri','bsAbd','bsSup'].reduce((a,k)=>a+num(bodyVal(k)),0);const e=document.getElementById('skinSumPreview');if(e)e.textContent=`Soma das dobras: ${fmt(s)} mm`};['bsTri','bsAbd','bsSup'].forEach(k=>document.getElementById(k)?.addEventListener('input',upd));upd();document.getElementById('saveBodySkin')?.addEventListener('click',async()=>{if(!bodyVal('bsDate')){toast('Informe a data');return}const fs=[{label:'Tricipital',mm:bodyNumOrBlank('bsTri')},{label:'Abdominal',mm:bodyNumOrBlank('bsAbd')},{label:'Suprailíaca',mm:bodyNumOrBlank('bsSup')}],sum=fs.reduce((s,f)=>s+num(f.mm),0);await bodySaveObject('Adipometria',{...x,id:id||`adipo-${Date.now()}`,userId:x.userId||'default',date:bodyVal('bsDate'),protocol:'3 dobras — Tricipital + Abdominal + Suprailíaca',measurements:JSON.stringify(fs),sumFoldsMm:sum,bodyDensity:bodyNumOrBlank('bsDensity'),bodyFatPct:bodyNumOrBlank('bsFatPct'),bodyFatClass:bodyVal('bsClass'),fatMassKg:bodyNumOrBlank('bsFatKg'),leanMassKg:bodyNumOrBlank('bsLeanKg'),weightKg:bodyNumOrBlank('bsWeight'),evaluationType:'Avaliação profissional',observations:bodyVal('bsNotes'),createdAt:x.createdAt||bodyNow(),source:bodyVal('bsSource')},id)})},0)}

function bodyEvaluationNewModal(){state.modal=`<div class="modalhead"><div><h3>Nova avaliação corporal</h3><div class="muted">Preencha somente os grupos realizados nesta avaliação.</div></div><button class="x" data-close>×</button></div>${bodyFormField('beDate','Data da avaliação',today(),'date','','required')}<details open><summary><strong>Peso</strong></summary><div class="formgrid">${bodyFormField('beWeight','Peso (kg)','')}</div></details><details><summary><strong>Medidas principais</strong></summary><div class="formgrid">${bodyFormField('beWaist','Cintura (cm)','')}${bodyFormField('beAbdomen','Abdômen (cm)','')}${bodyFormField('beHip','Quadril (cm)','')}${bodyFormField('beChest','Tórax (cm)','')}</div></details><details><summary><strong>Bioimpedância</strong></summary><div class="formgrid">${bodySelectField('beBioSource','Origem','Nutricionista',[['Nutricionista','Nutricionista — profissional'],['Casa','Casa — Relaxmedic/Fitdays']])}${bodyFormField('beBioFat','Gordura corporal (%)','')}${bodyFormField('beBioFatKg','Massa de gordura (kg)','')}${bodyFormField('beBioLean','Massa livre (kg)','')}${bodyFormField('beBioVisc','Gordura visceral','')}</div></details><details><summary><strong>Adipometria</strong></summary><div class="formgrid">${bodyFormField('beTri','Tricipital (mm)','')}${bodyFormField('beAbdFold','Abdominal (mm)','')}${bodyFormField('beSup','Suprailíaca (mm)','')}${bodyFormField('beAdFat','Gordura corporal (%)','')}${bodyFormField('beAdFatKg','Massa de gordura (kg)','')}${bodyFormField('beAdLean','Massa livre (kg)','')}</div></details><div class="actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveBodyEvaluation">Salvar avaliação</button></div>`;render();setTimeout(()=>document.getElementById('saveBodyEvaluation')?.addEventListener('click',saveBodyEvaluation),0)}
async function saveBodyEvaluation(){const d=bodyVal('beDate');if(!d){toast('Informe a data');return}const stamp=Date.now(),now=bodyNow();try{if(bodyVal('beWeight')){const h=rows(FILES.body,'Peso')[0].map(String),a=objRows(FILES.body,'Peso');a.push({id:`peso-eval-${stamp}`,userId:'default',date:d,weightKg:bodyNumOrBlank('beWeight'),createdAt:now,source:'Avaliação',notes:''});await saveSheet(FILES.body,'Peso',toRows(a,h))}if(['beWaist','beAbdomen','beHip','beChest'].some(k=>bodyVal(k))){const h=rows(FILES.body,'Medidas')[0].map(String),a=objRows(FILES.body,'Medidas');a.push({id:`med-eval-${stamp}`,userId:'default',date:d,cintura:bodyNumOrBlank('beWaist'),abdomen:bodyNumOrBlank('beAbdomen'),quadril:bodyNumOrBlank('beHip'),torax:bodyNumOrBlank('beChest'),createdAt:now,source:'Avaliação'});await saveSheet(FILES.body,'Medidas',toRows(a,h))}if(['beBioFat','beBioFatKg','beBioLean','beBioVisc'].some(k=>bodyVal(k))){const h=rows(FILES.body,'Bioimpedancia')[0].map(String),a=objRows(FILES.body,'Bioimpedancia');a.push({id:`bio-eval-${stamp}`,userId:'default',date:d,source:bodyVal('beBioSource'),equipment:'',appSource:'',observations:'',createdAt:now,weightKg:bodyNumOrBlank('beWeight'),bodyFatPct:bodyNumOrBlank('beBioFat'),fatMassPct:bodyNumOrBlank('beBioFat'),fatMassKg:bodyNumOrBlank('beBioFatKg'),fatFreeMassKg:bodyNumOrBlank('beBioLean'),visceralFat:bodyNumOrBlank('beBioVisc')});await saveSheet(FILES.body,'Bioimpedancia',toRows(a,h))}if(['beTri','beAbdFold','beSup','beAdFat'].some(k=>bodyVal(k))){const h=rows(FILES.body,'Adipometria')[0].map(String),a=objRows(FILES.body,'Adipometria'),fs=[{label:'Tricipital',mm:bodyNumOrBlank('beTri')},{label:'Abdominal',mm:bodyNumOrBlank('beAbdFold')},{label:'Suprailíaca',mm:bodyNumOrBlank('beSup')}];a.push({id:`adipo-eval-${stamp}`,userId:'default',date:d,protocol:'3 dobras — Tricipital + Abdominal + Suprailíaca',measurements:JSON.stringify(fs),sumFoldsMm:fs.reduce((s,f)=>s+num(f.mm),0),bodyFatPct:bodyNumOrBlank('beAdFat'),fatMassKg:bodyNumOrBlank('beAdFatKg'),leanMassKg:bodyNumOrBlank('beAdLean'),weightKg:bodyNumOrBlank('beWeight'),evaluationType:'Avaliação profissional',createdAt:now,source:'Nutricionista'});await saveSheet(FILES.body,'Adipometria',toRows(a,h))}state.modal=null;toast('Avaliação salva');render()}catch(e){toast('Erro ao salvar avaliação')}}

const _bodyWeightViewV42=bodyWeightView;bodyWeightView=function(){const w=bodyWeightRowsSorted(),base=_bodyWeightViewV42();return bodyActionBar('Adicionar peso','addBodyWeight')+base.replace(/<article class="body-record">/g,'<article class="body-record">').replace(/<\/article>/g,(m)=>m)};
const _bodyMeasuresViewV42=bodyMeasuresView;bodyMeasuresView=function(){const list=objRows(FILES.body,'Medidas').slice().reverse();if(!list.length)return bodyActionBar('Adicionar medidas','addBodyMeasures')+'<div class="card empty">Nenhuma medida registrada.</div>';return bodyActionBar('Adicionar medidas','addBodyMeasures')+`<div class="body-record-grid">${list.map(x=>`<article class="body-eval-card"><div class="body-card-head"><div><span class="body-kicker">Avaliação corporal</span><h3>${prettyDate(x.date)}</h3><small class="muted">${esc(x.source||'')}</small></div><div class="record-actions"><button class="btn" data-edit-measures="${esc(x.id)}">Editar</button><button class="btn danger" data-delete-body="Medidas|${esc(x.id)}">Excluir</button></div></div><div class="measure-group"><h4>Tronco</h4><div class="measure-grid">${measureChip('Pescoço',x.pescoco)}${measureChip('Tórax',x.torax)}${measureChip('Ombro',x.ombro)}${measureChip('Cintura',x.cintura)}${measureChip('Quadril',x.quadril)}${measureChip('Abdômen',x.abdomen)}</div></div><div class="measure-group"><h4>Membros superiores</h4><div class="measure-grid">${measureChip('Braço E relaxado',x.bracoEsqRelaxado)}${measureChip('Braço D relaxado',x.bracoDirRelaxado)}${measureChip('Braço E contraído',x.bracoEsqContraido)}${measureChip('Braço D contraído',x.bracoDirContraido)}${measureChip('Antebraço E',x.antebracoEsq)}${measureChip('Antebraço D',x.antebracoDir)}</div></div><div class="measure-group"><h4>Membros inferiores</h4><div class="measure-grid">${measureChip('Coxa E',x.coxaEsq)}${measureChip('Coxa D',x.coxaDir)}${measureChip('Panturrilha E',x.panturrilhaEsq)}${measureChip('Panturrilha D',x.panturrilhaDir)}</div></div></article>`).join('')}</div>`};
const _bodyBioViewV42=bodyBioView;bodyBioView=function(){const list=objRows(FILES.body,'Bioimpedancia').slice().reverse();if(!list.length)return bodyActionBar('Adicionar bioimpedância','addBodyBio')+'<div class="card empty">Nenhuma bioimpedância registrada.</div>';return bodyActionBar('Adicionar bioimpedância','addBodyBio')+`<div class="body-record-grid">${list.map(x=>`<article class="body-eval-card"><div class="body-card-head"><div><span class="body-kicker">${esc(x.source||'Bioimpedância')}</span><h3>${prettyDate(x.date)}</h3><small class="muted">${esc([x.equipment,x.appSource].filter(Boolean).join(' • '))}</small></div><div class="record-actions"><button class="btn" data-edit-bio="${esc(x.id)}">Editar</button><button class="btn danger" data-delete-body="Bioimpedancia|${esc(x.id)}">Excluir</button></div></div><div class="bio-grid">${bioMetric('Peso',x.weightKg,' kg')}${bioMetric('Gordura corporal',x.bodyFatPct||x.fatMassPct,'%')}${bioMetric('Massa de gordura',x.fatMassKg,' kg')}${bioMetric('Massa muscular',x.muscleMassKg,' kg')}${bioMetric('Massa livre de gordura',x.fatFreeMassKg,' kg')}${bioMetric('Água corporal',x.bodyWaterPct,'%')}${bioMetric('Gordura visceral',x.visceralFat,'')}${bioMetric('IMC',x.bmi,'')}${bioMetric('Metabolismo basal',x.bmrKcal,' kcal')}${bioMetric('Idade corporal',x.bodyAge,' anos')}</div></article>`).join('')}</div>`};
const _bodySkinViewV42=bodySkinView;bodySkinView=function(){const list=objRows(FILES.body,'Adipometria').slice().reverse();if(!list.length)return bodyActionBar('Adicionar adipometria','addBodySkin')+'<div class="card empty">Nenhuma adipometria registrada.</div>';return bodyActionBar('Adicionar adipometria','addBodySkin')+`<div class="body-record-grid">${list.map(x=>{const folds=parseFolds(x.measurements);return `<article class="body-eval-card"><div class="body-card-head"><div><span class="body-kicker">${esc(x.evaluationType||'Adipometria')}</span><h3>${prettyDate(x.date)}</h3><small class="muted">${esc(x.protocol||'')}</small></div><div class="record-actions"><button class="btn" data-edit-skin="${esc(x.id)}">Editar</button><button class="btn danger" data-delete-body="Adipometria|${esc(x.id)}">Excluir</button></div></div><div class="fold-grid">${folds.map(f=>`<div class="fold-card"><span>${esc(f.label||'Dobra')}</span><strong>${fmt(f.mm)} mm</strong></div>`).join('')}</div><div class="bio-grid skin-summary">${bioMetric('Soma das dobras',x.sumFoldsMm,' mm')}${bioMetric('Gordura corporal',x.bodyFatPct,'%')}${bioMetric('Massa de gordura',x.fatMassKg,' kg')}${bioMetric('Massa livre de gordura',x.leanMassKg,' kg')}${bioMetric('Densidade corporal',x.bodyDensity,'')}${x.bodyFatClass?`<div class="bio-metric"><span>Classificação</span><strong>${esc(x.bodyFatClass)}</strong></div>`:''}</div></article>`}).join('')}</div>`};
const _bodyEvaluationsV42=bodyEvaluations;bodyEvaluations=function(){return bodyActionBar('Nova avaliação','addBodyEvaluation')+_bodyEvaluationsV42()};

/* Peso: acrescenta ações por registro sem perder o gráfico/estatísticas atuais */
bodyWeightView=function(){const w=bodyWeightRowsSorted();let head=bodyActionBar('Adicionar peso','addBodyWeight');if(!w.length)return head+'<div class="card empty">Nenhum peso registrado.</div>';const last=w.at(-1),prev=w.at(-2),lv=weightVal(last),pv=prev?weightVal(prev):null;return head+`<div class="body-highlight"><div><span class="body-kicker">Último registro</span><strong>${fmt(lv)} kg</strong><small>${prettyDate(last.date)}</small></div>${prev?`<div class="body-delta ${lv-pv<=0?'good':''}"><span>Em relação ao registro anterior</span><strong>${lv-pv>0?'+':''}${fmt(lv-pv)} kg</strong></div>`:''}</div><div class="sectiontitle"><h3>Histórico de peso</h3><span class="muted">Leitura cronológica</span></div><div class="body-timeline">${w.slice().reverse().map((x,i)=>{const cur=weightVal(x),older=w[w.length-2-i],diff=older?cur-weightVal(older):null;return `<article class="body-record"><div class="body-record-date">${prettyDate(x.date)}</div><div class="body-record-main"><strong>${fmt(cur)} kg</strong>${diff!==null?`<span class="body-mini ${diff<=0?'good':''}">${diff>0?'+':''}${fmt(diff)} kg vs anterior</span>`:'<span class="body-mini">Primeiro registro</span>'}</div><div class="record-actions"><button class="btn" data-edit-weight="${esc(x.id)}">Editar</button><button class="btn danger" data-delete-body="Peso|${esc(x.id)}">Excluir</button></div></article>`}).join('')}</div>`};

const _bindV42Base=bind;bind=function(){_bindV42Base();document.getElementById('addBodyWeight')?.addEventListener('click',()=>bodyWeightModal());document.getElementById('addBodyMeasures')?.addEventListener('click',()=>bodyMeasuresModal());document.getElementById('addBodyBio')?.addEventListener('click',()=>bodyBioModal());document.getElementById('addBodySkin')?.addEventListener('click',()=>bodySkinModal());document.getElementById('addBodyEvaluation')?.addEventListener('click',bodyEvaluationNewModal);document.querySelectorAll('[data-edit-weight]').forEach(b=>b.onclick=()=>bodyWeightModal(b.dataset.editWeight));document.querySelectorAll('[data-edit-measures]').forEach(b=>b.onclick=()=>bodyMeasuresModal(b.dataset.editMeasures));document.querySelectorAll('[data-edit-bio]').forEach(b=>b.onclick=()=>bodyBioModal(b.dataset.editBio));document.querySelectorAll('[data-edit-skin]').forEach(b=>b.onclick=()=>bodySkinModal(b.dataset.editSkin));document.querySelectorAll('[data-delete-body]').forEach(b=>b.onclick=()=>{const [s,id]=b.dataset.deleteBody.split('|');bodyDeleteRecord(s,id)})};
